// templates/angular/src/app/components/modus-button.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcButton } from '@trimble-oss/moduswebcomponents-angular';

/**
 * Button color variant
 */
export type ButtonColor = 'primary' | 'secondary' | 'tertiary' | 'warning' | 'danger';

/**
 * Button style variant
 */
export type ButtonVariant = 'filled' | 'outlined' | 'borderless';

/**
 * Button size
 */
export type ButtonSize = 'xs' | 'sm' | 'md' | 'lg';

/**
 * Button shape
 */
export type ButtonShape = 'rectangle' | 'square' | 'circle';

/**
 * Icon position relative to button text
 */
export type IconPosition = 'left' | 'right' | 'only';

/**
 * Props for the ModusButton component
 */
export interface ModusButtonProps {
  /** The color of the button */
  color?: ButtonColor;
  /** The variant of the button */
  variant?: ButtonVariant;
  /** The size of the button */
  size?: ButtonSize;
  /** The shape of the button */
  shape?: ButtonShape;
  /** Whether the button is disabled */
  disabled?: boolean;
  /** Whether the button should take up the full width */
  fullWidth?: boolean;
  /** Whether the button is pressed (for toggle buttons) */
  pressed?: boolean;
  /** The type of the button */
  type?: 'button' | 'submit' | 'reset';
  /** An icon to display in the button */
  icon?: string;
  /** The position of the icon relative to the button text */
  iconPosition?: IconPosition;
  /** Icon size using Tailwind text utilities. If not provided, size is determined by button size and icon position */
  iconSize?:
    | 'text-2xs'
    | 'text-xs'
    | 'text-sm'
    | 'text-base'
    | 'text-lg'
    | 'text-xl'
    | 'text-2xl'
    | 'text-3xl'
    | 'text-4xl';
  /** The ARIA label for the button */
  ariaLabel?: string;
  /** A callback function to handle button clicks */
  onButtonClick?: () => void;
  /** A custom CSS class to apply to the button */
  className?: string;
}

/**
 * Renders a Modus button component with full customization support.
 *
 * @example
 * ```html
 * <!-- Basic button -->
 * <modus-button>Click me</modus-button>
 * ```
 *
 * @example
 * ```html
 * <!-- Icon button with custom styling -->
 * <modus-button
 *   icon="add"
 *   iconPosition="left"
 *   color="primary"
 *   size="lg"
 *   (buttonClick)="handleClick()"
 * >
 *   Add Item
 * </modus-button>
 * ```
 *
 * @example
 * ```html
 * <!-- Icon-only button with accessibility -->
 * <modus-button
 *   icon="settings"
 *   iconPosition="only"
 *   ariaLabel="Open settings"
 *   (buttonClick)="openSettings()"
 * ></modus-button>
 * ```
 */
@Component({
  selector: 'modus-button',
  standalone: true,
  imports: [CommonModule, ModusWcButton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-button
      [color]="color()"
      [variant]="variant()"
      [size]="size()"
      [shape]="shape()"
      [disabled]="disabled()"
      [fullWidth]="fullWidth()"
      [pressed]="pressed()"
      [type]="type()"
      [customClass]="className()"
      [attr.aria-label]="getAriaLabel()"
      (buttonClick)="handleButtonClick($event)"
    >
      @if (icon() && iconPosition() === 'left') {
      <i class="modus-icons {{ getIconSize() }} mr-2">{{ icon() }}</i>
      }
      <ng-content></ng-content>
      @if (icon() && iconPosition() === 'right') {
      <i class="modus-icons {{ getIconSize() }} ml-2">{{ icon() }}</i>
      } @if (icon() && iconPosition() === 'only') {
      <i class="modus-icons {{ getIconSize() }}">{{ icon() }}</i>
      }
    </modus-wc-button>
  `,
})
export class ModusButtonComponent {
  /** The color of the button */
  readonly color = input<ButtonColor>('primary');

  /** The variant of the button */
  readonly variant = input<ButtonVariant>('filled');

  /** The size of the button */
  readonly size = input<ButtonSize>('md');

  /** The shape of the button */
  readonly shape = input<ButtonShape>('rectangle');

  /** Whether the button is disabled */
  readonly disabled = input<boolean>(false);

  /** Whether the button should take up the full width */
  readonly fullWidth = input<boolean>(false);

  /** Whether the button is pressed (for toggle buttons) */
  readonly pressed = input<boolean>(false);

  /** The type of the button */
  readonly type = input<'button' | 'submit' | 'reset'>('button');

  /** An icon to display in the button */
  readonly icon = input<string | undefined>();

  /** The position of the icon relative to the button text */
  readonly iconPosition = input<IconPosition>('left');

  /** Icon size using Tailwind text utilities. If not provided, size is determined by button size and icon position */
  readonly iconSize = input<
    | 'text-2xs'
    | 'text-xs'
    | 'text-sm'
    | 'text-base'
    | 'text-lg'
    | 'text-xl'
    | 'text-2xl'
    | 'text-3xl'
    | 'text-4xl'
  >();

  /** The ARIA label for the button */
  readonly ariaLabel = input<string | undefined>();

  /** A custom CSS class to apply to the button */
  readonly className = input<string | undefined>();

  /** Callback function for button clicks (optional) */
  readonly onButtonClick = input<(() => void) | undefined>();

  /** Event emitter for button clicks */
  readonly buttonClick = output<MouseEvent | KeyboardEvent>();

  /**
   * Handles button click events from the Modus Web Component
   *
   * Emits the event to parent components and calls the optional callback
   *
   * @param event - The click or keyboard event from the button (from Stencil CustomEvent)
   */
  handleButtonClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    if (!this.disabled()) {
      // Extract the actual event from CustomEvent detail
      const actualEvent = event.detail;

      // Emit Angular event
      this.buttonClick.emit(actualEvent);

      // Call React-like callback if provided
      const callback = this.onButtonClick();
      if (callback) {
        callback();
      }
    }
  }

  /**
   * Determines the appropriate icon size based on button size, icon position, and explicit iconSize input.
   *
   * @returns The Tailwind text utility class for icon sizing
   */
  getIconSize(): string {
    // If iconSize is explicitly provided, use it
    const explicitSize = this.iconSize();
    if (explicitSize) {
      return explicitSize;
    }

    // Determine size based on button size and icon position
    const buttonSize = this.size();
    const position = this.iconPosition();

    // Icon-only buttons are generally larger
    if (position === 'only') {
      switch (buttonSize) {
        case 'xs':
          return 'text-sm'; // 12px
        case 'sm':
          return 'text-base'; // 14px
        case 'md':
          return 'text-xl'; // 18px (current default)
        case 'lg':
          return 'text-2xl'; // 20px
        default:
          return 'text-xl'; // 18px default
      }
    }

    // Icons with text (left/right position)
    switch (buttonSize) {
      case 'xs':
        return 'text-xs'; // 10px
      case 'sm':
        return 'text-sm'; // 12px
      case 'md':
        return 'text-lg'; // 16px (current default)
      case 'lg':
        return 'text-xl'; // 18px
      default:
        return 'text-lg'; // 16px default
    }
  }

  /**
   * Generates appropriate ARIA label for accessibility.
   *
   * For icon-only buttons, ensures proper accessibility by returning
   * the provided ariaLabel or falling back to undefined.
   *
   * @returns The appropriate ARIA label or undefined
   */
  getAriaLabel(): string | undefined {
    const ariaLabelValue = this.ariaLabel();
    if (ariaLabelValue) {
      return ariaLabelValue;
    }

    // For icon-only buttons, ariaLabel should be provided
    // If not provided, the component will rely on default ARIA behavior
    if (this.iconPosition() === 'only' && !ariaLabelValue) {
      // Note: In a production app, you might want to extract text content
      // from ng-content as a fallback, but that requires ViewChild and
      // content projection which is more complex
      return undefined;
    }

    return undefined;
  }
}

// templates/react/src/components/ModusButton.tsx
import { ModusWcButton } from "@trimble-oss/moduswebcomponents-react";
import type { ReactNode } from "react";

/**
 * Props for the ModusButton component.
 */
interface ModusButtonProps {
  /** The color of the button. */
  color?: "primary" | "secondary" | "tertiary" | "warning" | "danger";
  /** The variant of the button. */
  variant?: "filled" | "outlined" | "borderless";
  /** The size of the button. */
  size?: "xs" | "sm" | "md" | "lg";
  /** The shape of the button. */
  shape?: "rectangle" | "square" | "circle";

  /** Whether the button is disabled. */
  disabled?: boolean;
  /** Whether the button should take up the full width of its container. */
  fullWidth?: boolean;
  /** Whether the button is pressed. */
  pressed?: boolean;
  /** The type of the button. */
  type?: "button" | "submit" | "reset";

  /** The content to display inside the button. */
  children?: ReactNode;
  /** An icon to display in the button. */
  icon?: string;
  /** The position of the icon relative to the button text. */
  iconPosition?: "left" | "right" | "only";
  /** The size of the icon (Tailwind text class). */
  iconSize?: string;

  /** The ARIA label for the button. */
  ariaLabel?: string;

  /** A callback function to handle button clicks. */
  onButtonClick?: () => void;

  /** A custom CSS class to apply to the button. */
  className?: string;
}

/**
 * Renders a Modus button component with full customization support.
 *
 * @example
 * // Basic button
 * <ModusButton>Click me</ModusButton>
 *
 * @example
 * // Icon button with custom styling
 * <ModusButton
 *   icon="add"
 *   iconPosition="left"
 *   color="primary"
 *   size="lg"
 * >
 *   Add Item
 * </ModusButton>
 *
 * @example
 * // Icon-only button with accessibility
 * <ModusButton
 *   icon="settings"
 *   iconPosition="only"
 *   ariaLabel="Open settings"
 * />
 *
 * @param {ModusButtonProps} props - The component props.
 * @returns {JSX.Element} The rendered button component.
 * @see {@link https://modus.trimble.com/components/button} - Modus Button documentation
 */
export default function ModusButton({
  color,
  variant,
  size = "md",
  shape = "rectangle",
  disabled = false,
  fullWidth = false,
  pressed = false,
  type = "button",
  children,
  icon,
  iconPosition = "left",
  iconSize,
  ariaLabel,
  onButtonClick,
  className,
}: ModusButtonProps) {
  /**
   * Determines the appropriate icon size class based on button size, icon position, and explicit iconSize prop.
   *
   * @returns {string} The Tailwind text class for the icon size
   * @private
   */
  const getIconSizeClass = (): string => {
    // If iconSize is explicitly provided, use it
    if (iconSize) {
      return iconSize;
    }

    // Automatic sizing based on button size and icon position
    if (iconPosition === "only") {
      // Icon-only buttons get larger icons
      switch (size) {
        case "xs":
          return "text-sm";
        case "sm":
          return "text-base";
        case "md":
          return "text-xl";
        case "lg":
          return "text-2xl";
        default:
          return "text-xl";
      }
    } else {
      // Icons with text scale with button size
      switch (size) {
        case "xs":
          return "text-xs";
        case "sm":
          return "text-sm";
        case "md":
          return "text-lg";
        case "lg":
          return "text-xl";
        default:
          return "text-lg";
      }
    }
  };

  /**
   * Renders an icon with proper positioning and styling based on its position.
   *
   * This helper function creates an icon element with appropriate margin spacing
   * based on the icon's position relative to the button text. Icons positioned
   * on the left get right margin, icons on the right get left margin, and
   * icon-only buttons have no margin.
   *
   * @param {string} iconName - The name of the Modus icon to render
   * @param {"left" | "right" | "only"} position - The position of the icon relative to text
   * @returns {JSX.Element} The rendered icon element with appropriate styling
   * @private
   */
  const renderIcon = (
    iconName: string,
    position: "left" | "right" | "only",
  ) => {
    const iconStyle =
      position === "left"
        ? { marginRight: "8px" }
        : position === "right"
          ? { marginLeft: "8px" }
          : {};

    const iconSizeClass = getIconSizeClass();

    return (
      <i className={`modus-icons ${iconSizeClass}`} style={iconStyle}>
        {iconName}
      </i>
    );
  };

  /**
   * Determines and renders the button content based on icon position.
   *
   * This function handles the complex logic of combining icons and text content
   * based on the iconPosition prop. It supports three modes:
   * - "left": Icon appears before text
   * - "right": Icon appears after text
   * - "only": Only the icon is displayed (text is hidden)
   *
   * @returns {ReactNode} The rendered content with proper icon and text arrangement
   * @private
   */
  const renderContent = () => {
    if (!icon) {
      return children;
    }

    switch (iconPosition) {
      case "left":
        return (
          <>
            {renderIcon(icon, "left")}
            {children}
          </>
        );
      case "right":
        return (
          <>
            {children}
            {renderIcon(icon, "right")}
          </>
        );
      case "only":
        return renderIcon(icon, "only");
      default:
        return children;
    }
  };

  /**
   * Generates appropriate ARIA label for accessibility.
   *
   * This function ensures proper accessibility by generating ARIA labels
   * for icon-only buttons. If no explicit ariaLabel is provided and the
   * button is icon-only, it uses the text content as the aria-label.
   * This ensures screen readers can properly announce the button's purpose.
   *
   * @returns {string | undefined} The appropriate ARIA label or undefined
   * @private
   */
  const getAriaLabel = () => {
    if (ariaLabel) return ariaLabel;
    if (iconPosition === "only" && typeof children === "string") {
      return children; // Use text content as aria-label for icon-only buttons
    }
    return undefined;
  };

  return (
    <ModusWcButton
      {...(color && { color })}
      {...(variant && { variant })}
      size={size}
      shape={shape}
      disabled={disabled}
      fullWidth={fullWidth}
      pressed={pressed}
      type={type}
      aria-label={getAriaLabel()}
      onButtonClick={onButtonClick}
      custom-class={className}
    >
      {renderContent()}
    </ModusWcButton>
  );
}
