// templates/angular/src/app/components/modus-navbar.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcNavbar } from '@trimble-oss/moduswebcomponents-angular';
import type { Components } from '@trimble-oss/moduswebcomponents';

/**
 * Text replacements for the navbar.
 */
export interface INavbarTextOverrides {
  /** Replaces the text for "Apps" in the condensed menu. */
  apps?: string;
  /** Replaces the text for "Help" in the condensed menu. */
  help?: string;
  /** Replaces the text for "Notifications" in the condensed menu. */
  notifications?: string;
  /** Replaces the text for "Search" in the condensed menu. */
  search?: string;
}

/**
 * Controls the visibility of individual navbar buttons.
 */
export interface INavbarVisibility {
  /** Controls the visibility of the AI button. */
  ai?: boolean;
  /** Controls visibility of the apps button. */
  apps?: boolean;
  /** Controls visibility of the help button. */
  help?: boolean;
  /** Controls visibility of the main menu button. */
  mainMenu?: boolean;
  /** Controls visibility of the notifications button. */
  notifications?: boolean;
  /** Controls visibility of the search button. */
  search?: boolean;
  /** Controls visibility of the search input. */
  searchInput?: boolean;
  /** Controls visibility of the user button. */
  user?: boolean;
}

/**
 * User information used to render the user card.
 */
export interface INavbarUserCard {
  /** The alt value to set on the avatar. */
  avatarAlt?: string;
  /** The avatar image source value. */
  avatarSrc?: string;
  /** The email address of the user. */
  email: string;
  /** Text override for the Access MyTrimble button. */
  myTrimbleButton?: string;
  /** The name of the user. */
  name: string;
  /** Text override for the Sign out button. */
  signOutButton?: string;
}

/**
 * Props supported by the {@link ModusNavbarComponent}.
 */
export interface ModusNavbarProps {
  /** The open state of the apps menu. */
  appsMenuOpen?: Components.ModusWcNavbar['appsMenuOpen'];
  /** Applies condensed layout and styling. */
  condensed?: Components.ModusWcNavbar['condensed'];
  /** The open state of the condensed menu. */
  condensedMenuOpen?: Components.ModusWcNavbar['condensedMenuOpen'];
  /** Custom CSS class applied to the host element. */
  className?: Components.ModusWcNavbar['customClass'];
  /** The open state of the main menu. */
  mainMenuOpen?: Components.ModusWcNavbar['mainMenuOpen'];
  /** The open state of the notifications menu. */
  notificationsMenuOpen?: Components.ModusWcNavbar['notificationsMenuOpen'];
  /** Debounce time in milliseconds for search input changes. */
  searchDebounceMs?: Components.ModusWcNavbar['searchDebounceMs'];
  /** The open state of the search input. */
  searchInputOpen?: Components.ModusWcNavbar['searchInputOpen'];
  /** Text replacements for the navbar. */
  textOverrides?: INavbarTextOverrides;
  /** User information used to render the user card. */
  userCard: INavbarUserCard;
  /** The open state of the user menu. */
  userMenuOpen?: Components.ModusWcNavbar['userMenuOpen'];
  /** The visibility of individual navbar buttons. */
  visibility?: INavbarVisibility;
}

/**
 * Angular wrapper for the Modus navbar web component.
 *
 * The navbar component supports projecting custom content into several slots:
 * - `main-menu` slot: For custom main menu content
 * - `notifications` slot: For custom notifications menu content
 * - `apps` slot: For custom apps menu content
 * - `start` slot: For custom content at the start of the navbar
 * - `center` slot: For custom content at the center of the navbar
 * - `end` slot: For custom content at the end of the navbar
 *
 * @example
 * ```html
 * <modus-navbar
 *   [userCard]="userInfo"
 *   [visibility]="{ user: true, search: true }"
 *   (userMenuOpenChange)="handleUserMenuChange($event)"
 * />
 * ```
 */
@Component({
  selector: 'modus-navbar',
  imports: [CommonModule, ModusWcNavbar],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-navbar
      [appsMenuOpen]="appsMenuOpen()"
      [condensed]="condensed()"
      [condensedMenuOpen]="condensedMenuOpen()"
      [customClass]="className()"
      [mainMenuOpen]="mainMenuOpen()"
      [notificationsMenuOpen]="notificationsMenuOpen()"
      [searchDebounceMs]="searchDebounceMs()"
      [searchInputOpen]="searchInputOpen()"
      [textOverrides]="textOverrides()"
      [userCard]="userCard()"
      [userMenuOpen]="userMenuOpen()"
      [visibility]="visibility()"
      (aiClick)="handleAiClick($event)"
      (appsClick)="handleAppsClick($event)"
      (appsMenuOpenChange)="handleAppsMenuOpenChange($event)"
      (condensedMenuOpenChange)="handleCondensedMenuOpenChange($event)"
      (helpClick)="handleHelpClick($event)"
      (mainMenuOpenChange)="handleMainMenuOpenChange($event)"
      (myTrimbleClick)="handleMyTrimbleClick($event)"
      (notificationsClick)="handleNotificationsClick($event)"
      (notificationsMenuOpenChange)="handleNotificationsMenuOpenChange($event)"
      (searchChange)="handleSearchChange($event)"
      (searchClick)="handleSearchClick($event)"
      (searchInputOpenChange)="handleSearchInputOpenChange($event)"
      (signOutClick)="handleSignOutClick($event)"
      (trimbleLogoClick)="handleTrimbleLogoClick($event)"
      (userMenuOpenChange)="handleUserMenuOpenChange($event)"
    >
      <ng-content select="[slot='main-menu']" slot="main-menu" />
      <ng-content select="[slot='notifications']" slot="notifications" />
      <ng-content select="[slot='apps']" slot="apps" />
      <ng-content select="[slot='start']" slot="start" />
      <ng-content select="[slot='center']" slot="center" />
      <ng-content select="[slot='end']" slot="end" />
    </modus-wc-navbar>
  `,
})
export class ModusNavbarComponent {
  /** The open state of the apps menu. */
  readonly appsMenuOpen = input<boolean | undefined>(false);

  /** Applies condensed layout and styling. */
  readonly condensed = input<boolean | undefined>(false);

  /** The open state of the condensed menu. */
  readonly condensedMenuOpen = input<boolean | undefined>(false);

  /** Custom CSS class applied to the host element. */
  readonly className = input<string | undefined>();

  /** The open state of the main menu. */
  readonly mainMenuOpen = input<boolean | undefined>(false);

  /** The open state of the notifications menu. */
  readonly notificationsMenuOpen = input<boolean | undefined>(false);

  /** Debounce time in milliseconds for search input changes. */
  readonly searchDebounceMs = input<number | undefined>(300);

  /** The open state of the search input. */
  readonly searchInputOpen = input<boolean | undefined>(false);

  /** Text replacements for the navbar. */
  readonly textOverrides = input<INavbarTextOverrides | undefined>();

  /** User information used to render the user card. */
  readonly userCard = input.required<INavbarUserCard>();

  /** The open state of the user menu. */
  readonly userMenuOpen = input<boolean | undefined>(false);

  /** The visibility of individual navbar buttons. */
  readonly visibility = input<INavbarVisibility | undefined>({
    ai: false,
    apps: false,
    help: false,
    mainMenu: false,
    notifications: false,
    search: false,
    searchInput: false,
    user: true,
  });

  /** Emits when the AI button is clicked or activated via keyboard. */
  readonly aiClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the apps button is clicked or activated via keyboard. */
  readonly appsClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the apps menu open state changes. */
  readonly appsMenuOpenChange = output<boolean>();

  /** Emits when the condensed menu open state changes. */
  readonly condensedMenuOpenChange = output<boolean>();

  /** Emits when the help button is clicked or activated via keyboard. */
  readonly helpClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the main menu open state changes. */
  readonly mainMenuOpenChange = output<boolean>();

  /** Emits when the user profile Access MyTrimble button is clicked. */
  readonly myTrimbleClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the notifications button is clicked or activated via keyboard. */
  readonly notificationsClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the notifications menu open state changes. */
  readonly notificationsMenuOpenChange = output<boolean>();

  /** Emits when the search input value is changed. */
  readonly searchChange = output<{ value: string }>();

  /** Emits when the search button is clicked or activated via keyboard. */
  readonly searchClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the search input open state changes. */
  readonly searchInputOpenChange = output<boolean>();

  /** Emits when the user profile sign out button is clicked. */
  readonly signOutClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the Trimble logo is clicked or activated via keyboard. */
  readonly trimbleLogoClick = output<MouseEvent | KeyboardEvent>();

  /** Emits when the user menu open state changes. */
  readonly userMenuOpenChange = output<boolean>();

  handleAiClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.aiClick.emit(event.detail);
  }

  handleAppsClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.appsClick.emit(event.detail);
  }

  handleAppsMenuOpenChange(event: CustomEvent<boolean>): void {
    this.appsMenuOpenChange.emit(event.detail);
  }

  handleCondensedMenuOpenChange(event: CustomEvent<boolean>): void {
    this.condensedMenuOpenChange.emit(event.detail);
  }

  handleHelpClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.helpClick.emit(event.detail);
  }

  handleMainMenuOpenChange(event: CustomEvent<boolean>): void {
    this.mainMenuOpenChange.emit(event.detail);
  }

  handleMyTrimbleClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.myTrimbleClick.emit(event.detail);
  }

  handleNotificationsClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.notificationsClick.emit(event.detail);
  }

  handleNotificationsMenuOpenChange(event: CustomEvent<boolean>): void {
    this.notificationsMenuOpenChange.emit(event.detail);
  }

  handleSearchChange(event: CustomEvent<{ value: string }>): void {
    this.searchChange.emit(event.detail);
  }

  handleSearchClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.searchClick.emit(event.detail);
  }

  handleSearchInputOpenChange(event: CustomEvent<boolean>): void {
    this.searchInputOpenChange.emit(event.detail);
  }

  handleSignOutClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.signOutClick.emit(event.detail);
  }

  handleTrimbleLogoClick(event: CustomEvent<MouseEvent | KeyboardEvent>): void {
    this.trimbleLogoClick.emit(event.detail);
  }

  handleUserMenuOpenChange(event: CustomEvent<boolean>): void {
    this.userMenuOpenChange.emit(event.detail);
  }
}

// templates/react/src/components/ModusNavbar.tsx
import { ModusWcNavbar } from "@trimble-oss/moduswebcomponents-react";
import type { ReactNode } from "react";
import { useCallback, useEffect, useRef } from "react";

// Type definitions for navbar interfaces
interface NavbarUserCard {
  name: string;
  email: string;
  avatarSrc?: string;
  avatarAlt?: string;
}

interface NavbarVisibility {
  mainMenu?: boolean;
  search?: boolean;
  searchInput?: boolean;
  notifications?: boolean;
  apps?: boolean;
  ai?: boolean;
  help?: boolean;
  user?: boolean;
}

interface NavbarTextOverrides {
  apps?: string;
  help?: string;
  notifications?: string;
  search?: string;
}

/**
 * Props for the ModusNavbar component.
 */
interface ModusNavbarProps {
  /** Whether the navbar should be condensed. */
  condensed?: boolean;
  /** The user card information to display. */
  userCard: NavbarUserCard;
  /** Controls the visibility of different parts of the navbar. */
  visibility?: NavbarVisibility;
  /** Whether the main menu is open. */
  mainMenuOpen?: boolean;
  /** Whether the notifications menu is open. */
  notificationsMenuOpen?: boolean;
  /** Whether the apps menu is open. */
  appsMenuOpen?: boolean;
  /** Whether the search input is open. */
  searchInputOpen?: boolean;
  /** Whether the user menu is open. */
  userMenuOpen?: boolean;
  /** Whether the condensed menu is open. */
  condensedMenuOpen?: boolean;
  /** The debounce time in milliseconds for search input changes. */
  searchDebounceMs?: number;
  /** Text overrides for condensed mode. */
  textOverrides?: NavbarTextOverrides;
  /** A custom CSS class to apply to the navbar. */
  customClass?: string;
  /** The content to display in the main menu. */
  mainMenuContent?: ReactNode;
  /** The content to display in the notifications menu. */
  notificationsContent?: ReactNode;
  /** The content to display in the apps menu. */
  appsContent?: ReactNode;
  /** The content to display at the start of the navbar. */
  startContent?: ReactNode;
  /** The content to display in the center of the navbar. */
  centerContent?: ReactNode;
  /** The content to display at the end of the navbar. */
  endContent?: ReactNode;
  /** A callback function to handle AI clicks. */
  onAiClick?: () => void;
  /** A callback function to handle apps clicks. */
  onAppsClick?: () => void;
  /** A callback function to handle help clicks. */
  onHelpClick?: () => void;
  /** A callback function to handle notifications clicks. */
  onNotificationsClick?: () => void;
  /** A callback function to handle search clicks. */
  onSearchClick?: () => void;
  /** A callback function to handle sign out clicks. */
  onSignOutClick?: () => void;
  /** A callback function to handle "My Trimble" clicks. */
  onMyTrimbleClick?: () => void;
  /** A callback function to handle Trimble logo clicks. */
  onTrimbleLogoClick?: () => void;
  /** A callback function to handle search input changes. */
  onSearchChange?: (value: string) => void;
  /** A callback function to handle main menu open changes. */
  onMainMenuOpenChange?: (open: boolean) => void;
  /** A callback function to handle notifications menu open changes. */
  onNotificationsMenuOpenChange?: (open: boolean) => void;
  /** A callback function to handle apps menu open changes. */
  onAppsMenuOpenChange?: (open: boolean) => void;
  /** A callback function to handle search input open changes. */
  onSearchInputOpenChange?: (open: boolean) => void;
  /** A callback function to handle user menu open changes. */
  onUserMenuOpenChange?: (open: boolean) => void;
  /** A callback function to handle condensed menu open changes. */
  onCondensedMenuOpenChange?: (open: boolean) => void;
  /** The ARIA label for the navbar. */
  ariaLabel?: string;
}

/**
 * Renders a Modus navbar component.
 * @param {ModusNavbarProps} props - The component props.
 * @returns {JSX.Element} The rendered navbar component.
 */
export default function ModusNavbar({
  condensed = false,
  userCard,
  visibility = {
    mainMenu: true,
    search: true,
    searchInput: true,
    notifications: true,
    apps: true,
    ai: true,
    help: true,
    user: true,
  },
  mainMenuOpen = false,
  notificationsMenuOpen = false,
  appsMenuOpen = false,
  searchInputOpen = false,
  userMenuOpen = false,
  condensedMenuOpen = false,
  searchDebounceMs = 300,
  textOverrides,
  customClass,
  mainMenuContent,
  notificationsContent,
  appsContent,
  startContent,
  centerContent,
  endContent,
  onAiClick,
  onAppsClick,
  onHelpClick,
  onNotificationsClick,
  onSearchClick,
  onSignOutClick,
  onMyTrimbleClick,
  onTrimbleLogoClick,
  onSearchChange,
  onMainMenuOpenChange,
  onNotificationsMenuOpenChange,
  onAppsMenuOpenChange,
  onSearchInputOpenChange,
  onUserMenuOpenChange,
  onCondensedMenuOpenChange,
  ariaLabel,
}: ModusNavbarProps) {
  const navbarRef = useRef<HTMLElement>(null);
  const setNavbarRef = useCallback((element: HTMLElement | null) => {
    if (element) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const navbar = element as any;
      navbar.userCard = userCard;
      navbar.visibility = visibility;
      if (textOverrides) {
        navbar.textOverrides = textOverrides;
      }
      navbar.searchDebounceMs = searchDebounceMs;
      navbar.mainMenuOpen = mainMenuOpen;
      navbar.notificationsMenuOpen = notificationsMenuOpen;
      navbar.appsMenuOpen = appsMenuOpen;
      navbar.searchInputOpen = searchInputOpen;
      navbar.userMenuOpen = userMenuOpen;
      navbar.condensedMenuOpen = condensedMenuOpen;
    }
    navbarRef.current = element;
  }, [userCard, visibility, textOverrides, searchDebounceMs, mainMenuOpen, notificationsMenuOpen, appsMenuOpen, searchInputOpen, userMenuOpen, condensedMenuOpen]);

  // Event handlers with useCallback for performance
  /**
   * Handles AI button click events.
   *
   * @private
   */
  const handleAiClick = useCallback(() => {
    onAiClick?.();
  }, [onAiClick]);

  /**
   * Handles apps menu button click events.
   *
   * @private
   */
  const handleAppsClick = useCallback(() => {
    onAppsClick?.();
  }, [onAppsClick]);

  /**
   * Handles help button click events.
   *
   * @private
   */
  const handleHelpClick = useCallback(() => {
    onHelpClick?.();
  }, [onHelpClick]);

  /**
   * Handles notifications button click events.
   *
   * @private
   */
  const handleNotificationsClick = useCallback(() => {
    onNotificationsClick?.();
  }, [onNotificationsClick]);

  /**
   * Handles search button click events.
   *
   * @private
   */
  const handleSearchClick = useCallback(() => {
    onSearchClick?.();
  }, [onSearchClick]);

  /**
   * Handles sign out button click events.
   *
   * @private
   */
  const handleSignOutClick = useCallback(() => {
    onSignOutClick?.();
  }, [onSignOutClick]);

  /**
   * Handles My Trimble button click events.
   *
   * @private
   */
  const handleMyTrimbleClick = useCallback(() => {
    onMyTrimbleClick?.();
  }, [onMyTrimbleClick]);

  /**
   * Handles Trimble logo click events.
   *
   * @private
   */
  const handleTrimbleLogoClick = useCallback(() => {
    onTrimbleLogoClick?.();
  }, [onTrimbleLogoClick]);

  /**
   * Handles search input change events with debouncing.
   *
   * @param {Event} event - The search input change event
   * @private
   */
  const handleSearchChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<{ value: string }>;
      onSearchChange?.(customEvent.detail.value);
    },
    [onSearchChange]
  );

  /**
   * Handles main menu open/close state changes.
   *
   * @param {Event} event - The menu state change event
   * @private
   */
  const handleMainMenuOpenChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<boolean>;
      onMainMenuOpenChange?.(customEvent.detail);
    },
    [onMainMenuOpenChange]
  );

  /**
   * Handles notifications menu open/close state changes.
   *
   * @param {Event} event - The menu state change event
   * @private
   */
  const handleNotificationsMenuOpenChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<boolean>;
      onNotificationsMenuOpenChange?.(customEvent.detail);
    },
    [onNotificationsMenuOpenChange]
  );

  /**
   * Handles apps menu open/close state changes.
   *
   * @param {Event} event - The menu state change event
   * @private
   */
  const handleAppsMenuOpenChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<boolean>;
      onAppsMenuOpenChange?.(customEvent.detail);
    },
    [onAppsMenuOpenChange]
  );

  /**
   * Handles search input open/close state changes.
   *
   * @param {Event} event - The search input state change event
   * @private
   */
  const handleSearchInputOpenChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<boolean>;
      onSearchInputOpenChange?.(customEvent.detail);
    },
    [onSearchInputOpenChange]
  );

  /**
   * Handles user menu open/close state changes.
   *
   * @param {Event} event - The menu state change event
   * @private
   */
  const handleUserMenuOpenChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<boolean>;
      onUserMenuOpenChange?.(customEvent.detail);
    },
    [onUserMenuOpenChange]
  );

  /**
   * Handles condensed menu open/close state changes.
   *
   * @param {Event} event - The menu state change event
   * @private
   */
  const handleCondensedMenuOpenChange = useCallback(
    (event: Event) => {
      const customEvent = event as CustomEvent<boolean>;
      onCondensedMenuOpenChange?.(customEvent.detail);
    },
    [onCondensedMenuOpenChange]
  );

  // Set up event listeners when component mounts
  useEffect(() => {
    const navbar = navbarRef.current;
    if (!navbar) return;

    // Add event listeners
    navbar.addEventListener("aiClick", handleAiClick);
    navbar.addEventListener("appsClick", handleAppsClick);
    navbar.addEventListener("helpClick", handleHelpClick);
    navbar.addEventListener("notificationsClick", handleNotificationsClick);
    navbar.addEventListener("searchClick", handleSearchClick);
    navbar.addEventListener("signOutClick", handleSignOutClick);
    navbar.addEventListener("myTrimbleClick", handleMyTrimbleClick);
    navbar.addEventListener("trimbleLogoClick", handleTrimbleLogoClick);
    navbar.addEventListener("searchChange", handleSearchChange);
    navbar.addEventListener("mainMenuOpenChange", handleMainMenuOpenChange);
    navbar.addEventListener(
      "notificationsMenuOpenChange",
      handleNotificationsMenuOpenChange
    );
    navbar.addEventListener("appsMenuOpenChange", handleAppsMenuOpenChange);
    navbar.addEventListener(
      "searchInputOpenChange",
      handleSearchInputOpenChange
    );
    navbar.addEventListener("userMenuOpenChange", handleUserMenuOpenChange);
    navbar.addEventListener(
      "condensedMenuOpenChange",
      handleCondensedMenuOpenChange
    );

    // Cleanup event listeners
    return () => {
      navbar.removeEventListener("aiClick", handleAiClick);
      navbar.removeEventListener("appsClick", handleAppsClick);
      navbar.removeEventListener("helpClick", handleHelpClick);
      navbar.removeEventListener(
        "notificationsClick",
        handleNotificationsClick
      );
      navbar.removeEventListener("searchClick", handleSearchClick);
      navbar.removeEventListener("signOutClick", handleSignOutClick);
      navbar.removeEventListener("myTrimbleClick", handleMyTrimbleClick);
      navbar.removeEventListener("trimbleLogoClick", handleTrimbleLogoClick);
      navbar.removeEventListener("searchChange", handleSearchChange);
      navbar.removeEventListener(
        "mainMenuOpenChange",
        handleMainMenuOpenChange
      );
      navbar.removeEventListener(
        "notificationsMenuOpenChange",
        handleNotificationsMenuOpenChange
      );
      navbar.removeEventListener(
        "appsMenuOpenChange",
        handleAppsMenuOpenChange
      );
      navbar.removeEventListener(
        "searchInputOpenChange",
        handleSearchInputOpenChange
      );
      navbar.removeEventListener(
        "userMenuOpenChange",
        handleUserMenuOpenChange
      );
      navbar.removeEventListener(
        "condensedMenuOpenChange",
        handleCondensedMenuOpenChange
      );
    };
  }, [
    handleAiClick,
    handleAppsClick,
    handleHelpClick,
    handleNotificationsClick,
    handleSearchClick,
    handleSignOutClick,
    handleMyTrimbleClick,
    handleTrimbleLogoClick,
    handleSearchChange,
    handleMainMenuOpenChange,
    handleNotificationsMenuOpenChange,
    handleAppsMenuOpenChange,
    handleSearchInputOpenChange,
    handleUserMenuOpenChange,
    handleCondensedMenuOpenChange,
  ]);

  // Update navbar properties when props change
  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const navbar = navbarRef.current as any;
    if (!navbar) return;

    // Update visibility
    navbar.visibility = visibility;

    // Update user card
    navbar.userCard = userCard;

    // Update text overrides
    if (textOverrides) {
      navbar.textOverrides = textOverrides;
    }

    // Update search debounce
    navbar.searchDebounceMs = searchDebounceMs;

    // Update menu states
    navbar.mainMenuOpen = mainMenuOpen;
    navbar.notificationsMenuOpen = notificationsMenuOpen;
    navbar.appsMenuOpen = appsMenuOpen;
    navbar.searchInputOpen = searchInputOpen;
    navbar.userMenuOpen = userMenuOpen;
    navbar.condensedMenuOpen = condensedMenuOpen;
  }, [
    visibility,
    userCard,
    textOverrides,
    searchDebounceMs,
    mainMenuOpen,
    notificationsMenuOpen,
    appsMenuOpen,
    searchInputOpen,
    userMenuOpen,
    condensedMenuOpen,
  ]);

  return (
    <ModusWcNavbar
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      ref={setNavbarRef as any}
      condensed={condensed}
      custom-class={customClass}
      aria-label={ariaLabel}
    >
      {/* Main Menu Slot */}
      {mainMenuContent && <div slot="main-menu">{mainMenuContent}</div>}

      {/* Notifications Slot */}
      {notificationsContent && (
        <div slot="notifications">{notificationsContent}</div>
      )}

      {/* Apps Slot */}
      {appsContent && <div slot="apps">{appsContent}</div>}

      {/* Start Slot */}
      {startContent && <div slot="start">{startContent}</div>}

      {/* Center Slot */}
      {centerContent && <div slot="center">{centerContent}</div>}

      {/* End Slot */}
      {endContent && <div slot="end">{endContent}</div>}
    </ModusWcNavbar>
  );
}
