// templates/angular/src/app/components/modus-date.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcDate } from '@trimble-oss/moduswebcomponents-angular';
import type {
  Components,
  DaisySize,
  IInputFeedbackProp,
  WeekStartDay,
} from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusDateComponent}.
 */
export interface ModusDateProps {
  /** Enables the bordered input style. */
  bordered?: Components.ModusWcDate['bordered'];
  /** Custom CSS class applied to the host element. */
  className?: Components.ModusWcDate['customClass'];
  /** Disables input interaction. */
  disabled?: Components.ModusWcDate['disabled'];
  /** Feedback message displayed below the control. */
  feedback?: IInputFeedbackProp;
  /** Date format pattern. */
  format?: 'yyyy-mm-dd' | 'dd-mm-yyyy' | 'yyyy/mm/dd' | 'dd/mm/yyyy' | 'MMM DD, YYYY';
  /** Identifier applied to the native input. */
  inputId?: Components.ModusWcDate['inputId'];
  /** Tab index applied to the native input. */
  inputTabIndex?: Components.ModusWcDate['inputTabIndex'];
  /** Input label text. */
  label?: Components.ModusWcDate['label'];
  /** Maximum allowed date value. */
  max?: Components.ModusWcDate['max'];
  /** Minimum allowed date value. */
  min?: Components.ModusWcDate['min'];
  /** Name attribute submitted in forms. */
  name?: Components.ModusWcDate['name'];
  /** Puts the input in read-only mode. */
  readOnly?: Components.ModusWcDate['readOnly'];
  /** Marks the input as required. */
  required?: Components.ModusWcDate['required'];
  /** Control size token. */
  size?: DaisySize;
  /** Current date value. */
  value?: Components.ModusWcDate['value'];
  /** First day of the week for the calendar view. */
  weekStartDay?: WeekStartDay;
}

/**
 * Angular wrapper for the Modus date input web component.
 */
@Component({
  selector: 'modus-date',
  imports: [CommonModule, ModusWcDate],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-date
      [bordered]="bordered()"
      [customClass]="className()"
      [disabled]="disabled()"
      [feedback]="feedback()"
      [format]="format()"
      [inputId]="inputId()"
      [inputTabIndex]="inputTabIndex()"
      [label]="label()"
      [max]="max()"
      [min]="min()"
      [name]="name()"
      [readOnly]="readOnly()"
      [required]="required()"
      [size]="size()"
      [value]="value()"
      [weekStartDay]="weekStartDay()"
      (inputBlur)="handleBlur($event)"
      (inputChange)="handleChange($event)"
      (inputFocus)="handleFocus($event)"
      (calendarMonthChange)="handleCalendarMonthChange($event)"
      (calendarYearChange)="handleCalendarYearChange($event)"
    />
  `,
})
export class ModusDateComponent {
  /** Enables the bordered input style. */
  readonly bordered = input<boolean | undefined>(true);

  /** Custom CSS class applied to the host element. */
  readonly className = input<string | undefined>();

  /** Disables input interaction. */
  readonly disabled = input<boolean | undefined>(false);

  /** Feedback message displayed below the control. */
  readonly feedback = input<IInputFeedbackProp | undefined>();

  /** Date format pattern. */
  readonly format = input<'yyyy-mm-dd' | 'dd-mm-yyyy' | 'yyyy/mm/dd' | 'dd/mm/yyyy' | 'MMM DD, YYYY' | undefined>('dd-mm-yyyy');

  /** Identifier applied to the native input. */
  readonly inputId = input<string | undefined>();

  /** Tab index applied to the native input. */
  readonly inputTabIndex = input<number | undefined>();

  /** Input label text. */
  readonly label = input<string | undefined>();

  /** Maximum allowed date value. */
  readonly max = input<string | undefined>();

  /** Minimum allowed date value. */
  readonly min = input<string | undefined>();

  /** Name attribute submitted in forms. */
  readonly name = input<string | undefined>('');

  /** Puts the input in read-only mode. */
  readonly readOnly = input<boolean | undefined>(false);

  /** Marks the input as required. */
  readonly required = input<boolean | undefined>(false);

  /** Control size token. */
  readonly size = input<DaisySize | undefined>('md');

  /** Current date value. */
  readonly value = input<string | undefined>();

  /** First day of the week for the calendar view. */
  readonly weekStartDay = input<WeekStartDay | undefined>('sunday');

  /** Emits when the input loses focus. */
  readonly inputBlur = output<FocusEvent>();

  /** Emits when the value changes. */
  readonly inputChange = output<InputEvent>();

  /** Emits when the input gains focus. */
  readonly inputFocus = output<FocusEvent>();

  /** Emits when the calendar month selection changes. */
  readonly calendarMonthChange = output<number>();

  /** Emits when the calendar year selection changes. */
  readonly calendarYearChange = output<number>();

  handleBlur(event: CustomEvent<FocusEvent>): void {
    this.inputBlur.emit(event.detail);
  }

  handleChange(event: CustomEvent<InputEvent>): void {
    this.inputChange.emit(event.detail);
  }

  handleFocus(event: CustomEvent<FocusEvent>): void {
    this.inputFocus.emit(event.detail);
  }

  handleCalendarMonthChange(event: CustomEvent<number>): void {
    this.calendarMonthChange.emit(event.detail);
  }

  handleCalendarYearChange(event: CustomEvent<number>): void {
    this.calendarYearChange.emit(event.detail);
  }
}

// templates/react/src/components/ModusDate.tsx
import { useEffect, useRef } from "react";
import { ModusWcDate } from "@trimble-oss/moduswebcomponents-react";

/**
 * Represents feedback for an input component.
 */
export interface InputFeedbackProp {
  /** The severity level of the feedback. */
  level: "error" | "info" | "success" | "warning";
  /** The message to display as feedback. */
  message?: string;
}

/** Date format options. */
export type DateFormat =
  | "yyyy-mm-dd"
  | "dd-mm-yyyy"
  | "yyyy/mm/dd"
  | "dd/mm/yyyy"
  | "MMM DD, YYYY";

/** Week start day options. */
export type WeekStartDay = "sunday" | "monday";

/**
 * Props for the ModusDate component.
 */
export interface ModusDateProps {
  /** The value of the date input (Format: YYYY-MM-DD). */
  value?: string;
  /** Whether the date input has a border. */
  bordered?: boolean;
  /** Whether the date input is disabled. */
  disabled?: boolean;
  /** Feedback to display for the date input. */
  feedback?: InputFeedbackProp;
  /** Date format pattern. */
  format?: DateFormat;
  /** The ID of the input element. */
  inputId?: string;
  /** The tab index of the input element. */
  inputTabIndex?: number;
  /** The label for the date input. */
  label?: string;
  /** The maximum allowed date (Format: YYYY-MM-DD). */
  max?: string;
  /** The minimum allowed date (Format: YYYY-MM-DD). */
  min?: string;
  /** The name of the input element. */
  name?: string;
  /** Whether the date input is read-only. */
  readOnly?: boolean;
  /** Whether the date input is required. */
  required?: boolean;
  /** The size of the date input. */
  size?: "sm" | "md" | "lg";
  /** First day of the week for the calendar view. */
  weekStartDay?: WeekStartDay;
  /** A custom CSS class to apply to the date input. */
  customClass?: string;
  /** The ARIA label for the date input. */
  "aria-label"?: string;
  /** A callback function to handle input changes. */
  onInputChange?: (event: CustomEvent<InputEvent>) => void;
  /** A callback function to handle input focus. */
  onInputFocus?: (event: CustomEvent<FocusEvent>) => void;
  /** A callback function to handle input blur. */
  onInputBlur?: (event: CustomEvent<FocusEvent>) => void;
}

/**
 * Renders a Modus date input component.
 * @param {ModusDateProps} props - The component props.
 * @returns {JSX.Element} The rendered date input component.
 */
export default function ModusDate({
  value = "",
  bordered = true,
  disabled = false,
  feedback,
  format,
  inputId,
  inputTabIndex,
  label,
  max,
  min,
  name = "",
  readOnly = false,
  required = false,
  size = "md",
  weekStartDay,
  customClass,
  "aria-label": ariaLabel,
  onInputChange,
  onInputFocus,
  onInputBlur,
}: ModusDateProps) {
  const dateRef = useRef<HTMLModusWcDateElement>(null);

  useEffect(() => {
    const date = dateRef.current;
    if (!date) return;

    const handleInputChange = (event: Event) => {
      onInputChange?.(event as CustomEvent<InputEvent>);
    };
    const handleInputFocus = (event: Event) => {
      onInputFocus?.(event as CustomEvent<FocusEvent>);
    };
    const handleInputBlur = (event: Event) => {
      onInputBlur?.(event as CustomEvent<FocusEvent>);
    };

    if (onInputChange) date.addEventListener("inputChange", handleInputChange);
    if (onInputFocus) date.addEventListener("inputFocus", handleInputFocus);
    if (onInputBlur) date.addEventListener("inputBlur", handleInputBlur);

    return () => {
      if (onInputChange)
        date.removeEventListener("inputChange", handleInputChange);
      if (onInputFocus)
        date.removeEventListener("inputFocus", handleInputFocus);
      if (onInputBlur) date.removeEventListener("inputBlur", handleInputBlur);
    };
  }, [onInputChange, onInputFocus, onInputBlur]);

  // Note: format and weekStartDay are passed as attributes since they may not be
  // exposed as typed props in the React bindings but are supported by the web component
  const additionalProps: Record<string, unknown> = {};
  if (format) additionalProps.format = format;
  if (weekStartDay) additionalProps.weekStartDay = weekStartDay;

  return (
    <ModusWcDate
      ref={dateRef}
      value={value}
      bordered={bordered}
      disabled={disabled}
      feedback={feedback}
      inputId={inputId}
      inputTabIndex={inputTabIndex}
      label={label}
      max={max}
      min={min}
      name={name}
      readOnly={readOnly}
      required={required}
      size={size}
      customClass={customClass}
      aria-label={ariaLabel}
      {...additionalProps}
    />
  );
}
