// templates/angular/src/app/components/modus-handle.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcHandle } from '@trimble-oss/moduswebcomponents-angular';
import type { Components } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusHandleComponent}.
 */
export interface ModusHandleProps {
  /** Custom CSS class applied to the handle. */
  className?: Components.ModusWcHandle['customClass'];
  /** Initial split percentage for the left/top panel. */
  defaultSplit?: Components.ModusWcHandle['defaultSplit'];
  /** Density token controlling handle spacing. */
  density?: Components.ModusWcHandle['density'];
  /** Left/top target element or selector. */
  leftTarget?: Components.ModusWcHandle['leftTarget'];
  /** Right/bottom target element or selector. */
  rightTarget?: Components.ModusWcHandle['rightTarget'];
  /** Orientation of the handle. */
  orientation?: Components.ModusWcHandle['orientation'];
  /** Size of the handle bar. */
  size?: Components.ModusWcHandle['size'];
  /** Handle type (bar or button). */
  type?: Components.ModusWcHandle['type'];
  /** Button color for button-style handles. */
  buttonColor?: Components.ModusWcHandle['buttonColor'];
  /** Button size for button-style handles. */
  buttonSize?: Components.ModusWcHandle['buttonSize'];
  /** Button variant for button-style handles. */
  buttonVariant?: Components.ModusWcHandle['buttonVariant'];
  /** Accessible label for the handle. */
  ariaLabel?: string;
}

/**
 * Angular wrapper for the Modus handle web component.
 */
@Component({
  selector: 'modus-handle',
  imports: [CommonModule, ModusWcHandle],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-handle
      [customClass]="className()"
      [defaultSplit]="defaultSplit()"
      [density]="density()"
      [leftTarget]="leftTarget()"
      [rightTarget]="rightTarget()"
      [orientation]="orientation()"
      [size]="size()"
      [type]="type()"
      [buttonColor]="buttonColor()"
      [buttonSize]="buttonSize()"
      [buttonVariant]="buttonVariant()"
      [attr.aria-label]="ariaLabel()"
    />
  `,
})
export class ModusHandleComponent {
  /** Custom CSS class applied to the handle. */
  readonly className = input<string | undefined>();

  /** Initial split percentage for the left/top panel. */
  readonly defaultSplit = input<Components.ModusWcHandle['defaultSplit'] | undefined>();

  /** Density token controlling handle spacing. */
  readonly density = input<Components.ModusWcHandle['density'] | undefined>();

  /** Left/top target element or selector. */
  readonly leftTarget = input<Components.ModusWcHandle['leftTarget'] | undefined>();

  /** Right/bottom target element or selector. */
  readonly rightTarget = input<Components.ModusWcHandle['rightTarget'] | undefined>();

  /** Orientation of the handle. */
  readonly orientation = input<Components.ModusWcHandle['orientation'] | undefined>('horizontal');

  /** Size of the handle bar. */
  readonly size = input<Components.ModusWcHandle['size'] | undefined>('default');

  /** Handle type (bar or button). */
  readonly type = input<Components.ModusWcHandle['type'] | undefined>('bar');

  /** Button color for button-style handles. */
  readonly buttonColor = input<Components.ModusWcHandle['buttonColor'] | undefined>('tertiary');

  /** Button size for button-style handles. */
  readonly buttonSize = input<Components.ModusWcHandle['buttonSize'] | undefined>('md');

  /** Button variant for button-style handles. */
  readonly buttonVariant = input<Components.ModusWcHandle['buttonVariant'] | undefined>('filled');

  /** Accessible label for the handle. */
  readonly ariaLabel = input<string | undefined>();
}

// templates/react/src/components/ModusHandle.tsx
import { ModusWcHandle } from "@trimble-oss/moduswebcomponents-react";

/**
 * Props for the ModusHandle component.
 */
export interface ModusHandleProps {
  /** Custom CSS class to apply to the handle element. */
  customClass?: string;
  /** Initial split percentage (1-100) for the left/top panel. */
  defaultSplit?: number;
  /** Spacing/density of the handle container. */
  density?: "compact" | "comfortable" | "relaxed";
  /** CSS selector or HTMLElement reference for the left/top panel to resize. */
  leftTarget?: string;
  /** Orientation of the handle (horizontal resizes left/right, vertical resizes top/bottom). */
  orientation?: "horizontal" | "vertical";
  /** CSS selector or HTMLElement reference for the right/bottom panel to resize. */
  rightTarget?: string;
  /** Size of the handle bar. */
  size?: "default" | "lg" | "xl" | "2xl";
  /** Type of handle to display - simple bar or button with drag icon. */
  type?: "bar" | "button";
  /** Color of the button (only applies when type="button"). */
  buttonColor?: "primary" | "secondary" | "tertiary" | "warning" | "danger";
  /** Size of the button (only applies when type="button"). */
  buttonSize?: "xs" | "sm" | "md" | "lg";
  /** Variant of the button (only applies when type="button"). */
  buttonVariant?: "borderless" | "filled" | "outlined";
  /** The ARIA label for the handle. */
  ariaLabel?: string;
}

/**
 * Renders a Modus handle component for resizing adjacent elements.
 *
 * @example
 * // Basic horizontal handle
 * <div className="flex h-[300px]">
 *   <div id="left-panel" className="w-[200px]">Left</div>
 *   <ModusHandle
 *     orientation="horizontal"
 *     leftTarget="#left-panel"
 *     rightTarget="#right-panel"
 *   />
 *   <div id="right-panel" className="flex-1">Right</div>
 * </div>
 *
 * @example
 * // Button type handle
 * <ModusHandle
 *   type="button"
 *   orientation="horizontal"
 *   buttonColor="primary"
 *   buttonVariant="outlined"
 *   leftTarget="#panel-a"
 *   rightTarget="#panel-b"
 * />
 *
 * @example
 * // With custom split percentage
 * <ModusHandle
 *   orientation="horizontal"
 *   defaultSplit={30}
 *   leftTarget="#left"
 *   rightTarget="#right"
 * />
 *
 * @param {ModusHandleProps} props - The component props.
 * @returns {JSX.Element} The rendered handle component.
 */
export default function ModusHandle({
  customClass,
  defaultSplit = 50,
  density = "comfortable",
  leftTarget,
  orientation = "horizontal",
  rightTarget,
  size = "default",
  type = "bar",
  buttonColor = "tertiary",
  buttonSize = "md",
  buttonVariant = "filled",
  ariaLabel,
}: ModusHandleProps) {
  return (
    <ModusWcHandle
      custom-class={customClass}
      default-split={defaultSplit}
      density={density}
      left-target={leftTarget}
      orientation={orientation}
      right-target={rightTarget}
      size={size}
      type={type}
      button-color={buttonColor}
      button-size={buttonSize}
      button-variant={buttonVariant}
      aria-label={ariaLabel}
    />
  );
}
