// templates/solidjs/src/components/ModusButton.tsx
import type { Component, JSX } from "solid-js";

/**
 * Props for the ModusButton component.
 */
interface ModusButtonProps {
  color?: "primary" | "secondary" | "tertiary" | "warning" | "danger";
  variant?: "filled" | "outlined" | "borderless";
  size?: "xs" | "sm" | "md" | "lg";
  shape?: "rectangle" | "square" | "circle";
  disabled?: boolean;
  fullWidth?: boolean;
  pressed?: boolean;
  type?: "button" | "submit" | "reset";
  children?: JSX.Element;
  icon?: string;
  iconPosition?: "left" | "right" | "only";
  iconSize?: string;
  ariaLabel?: string;
  onButtonClick?: () => void;
  className?: string;
}

/**
 * Renders a Modus button component.
 *
 * @param {ModusButtonProps} props - The component props.
 * @returns {JSX.Element} The rendered button component.
 */
const ModusButton: Component<ModusButtonProps> = (props) => {
  const getIconSizeClass = (): string => {
    if (props.iconSize) return props.iconSize;
    if (props.iconPosition === "only") {
      switch (props.size) {
        case "xs": return "text-sm";
        case "sm": return "text-base";
        case "md": return "text-xl";
        case "lg": return "text-2xl";
        default: return "text-xl";
      }
    }
    switch (props.size) {
      case "xs": return "text-xs";
      case "sm": return "text-sm";
      case "md": return "text-lg";
      case "lg": return "text-xl";
      default: return "text-lg";
    }
  };

  const renderIcon = (iconName: string, position: "left" | "right" | "only") => {
    const iconStyle =
      position === "left"
        ? { marginRight: "8px" }
        : position === "right"
          ? { marginLeft: "8px" }
          : {};
    return (
      <i class={`modus-icons ${getIconSizeClass()}`} style={iconStyle}>
        {iconName}
      </i>
    );
  };

  const renderContent = (): JSX.Element => {
    if (!props.icon) return props.children as JSX.Element;
    switch (props.iconPosition) {
      case "left":
        return (
          <>
            {renderIcon(props.icon, "left")}
            {props.children}
          </>
        );
      case "right":
        return (
          <>
            {props.children}
            {renderIcon(props.icon, "right")}
          </>
        );
      case "only":
        return renderIcon(props.icon, "only");
      default:
        return props.children as JSX.Element;
    }
  };

  const getAriaLabel = () => {
    if (props.ariaLabel) return props.ariaLabel;
    if (props.iconPosition === "only" && typeof props.children === "string") {
      return props.children;
    }
    return undefined;
  };

  return (
    <modus-wc-button
      {...(props.color && { color: props.color })}
      {...(props.variant && { variant: props.variant })}
      size={props.size ?? "md"}
      shape={props.shape ?? "rectangle"}
      disabled={props.disabled ?? false}
      fullWidth={props.fullWidth ?? false}
      pressed={props.pressed ?? false}
      type={props.type ?? "button"}
      aria-label={getAriaLabel()}
      custom-class={props.className}
      on:buttonClick={() => props.onButtonClick?.()}
    >
      {renderContent()}
    </modus-wc-button>
  );
};

export default ModusButton;

// templates/react/src/components/ModusButton.tsx
import { ModusWcButton } from "@trimble-oss/moduswebcomponents-react";
import type { ReactNode } from "react";

/**
 * Props for the ModusButton component.
 */
interface ModusButtonProps {
  /** The color of the button. */
  color?: "primary" | "secondary" | "tertiary" | "warning" | "danger";
  /** The variant of the button. */
  variant?: "filled" | "outlined" | "borderless";
  /** The size of the button. */
  size?: "xs" | "sm" | "md" | "lg";
  /** The shape of the button. */
  shape?: "rectangle" | "square" | "circle";

  /** Whether the button is disabled. */
  disabled?: boolean;
  /** Whether the button should take up the full width of its container. */
  fullWidth?: boolean;
  /** Whether the button is pressed. */
  pressed?: boolean;
  /** The type of the button. */
  type?: "button" | "submit" | "reset";

  /** The content to display inside the button. */
  children?: ReactNode;
  /** An icon to display in the button. */
  icon?: string;
  /** The position of the icon relative to the button text. */
  iconPosition?: "left" | "right" | "only";
  /** The size of the icon (Tailwind text class). */
  iconSize?: string;

  /** The ARIA label for the button. */
  ariaLabel?: string;

  /** A callback function to handle button clicks. */
  onButtonClick?: () => void;

  /** A custom CSS class to apply to the button. */
  className?: string;
}

/**
 * Renders a Modus button component with full customization support.
 *
 * @example
 * // Basic button
 * <ModusButton>Click me</ModusButton>
 *
 * @example
 * // Icon button with custom styling
 * <ModusButton
 *   icon="add"
 *   iconPosition="left"
 *   color="primary"
 *   size="lg"
 * >
 *   Add Item
 * </ModusButton>
 *
 * @example
 * // Icon-only button with accessibility
 * <ModusButton
 *   icon="settings"
 *   iconPosition="only"
 *   ariaLabel="Open settings"
 * />
 *
 * @param {ModusButtonProps} props - The component props.
 * @returns {JSX.Element} The rendered button component.
 * @see {@link https://modus.trimble.com/components/button} - Modus Button documentation
 */
export default function ModusButton({
  color,
  variant,
  size = "md",
  shape = "rectangle",
  disabled = false,
  fullWidth = false,
  pressed = false,
  type = "button",
  children,
  icon,
  iconPosition = "left",
  iconSize,
  ariaLabel,
  onButtonClick,
  className,
}: ModusButtonProps) {
  /**
   * Determines the appropriate icon size class based on button size, icon position, and explicit iconSize prop.
   *
   * @returns {string} The Tailwind text class for the icon size
   * @private
   */
  const getIconSizeClass = (): string => {
    // If iconSize is explicitly provided, use it
    if (iconSize) {
      return iconSize;
    }

    // Automatic sizing based on button size and icon position
    if (iconPosition === "only") {
      // Icon-only buttons get larger icons
      switch (size) {
        case "xs":
          return "text-sm";
        case "sm":
          return "text-base";
        case "md":
          return "text-xl";
        case "lg":
          return "text-2xl";
        default:
          return "text-xl";
      }
    } else {
      // Icons with text scale with button size
      switch (size) {
        case "xs":
          return "text-xs";
        case "sm":
          return "text-sm";
        case "md":
          return "text-lg";
        case "lg":
          return "text-xl";
        default:
          return "text-lg";
      }
    }
  };

  /**
   * Renders an icon with proper positioning and styling based on its position.
   *
   * This helper function creates an icon element with appropriate margin spacing
   * based on the icon's position relative to the button text. Icons positioned
   * on the left get right margin, icons on the right get left margin, and
   * icon-only buttons have no margin.
   *
   * @param {string} iconName - The name of the Modus icon to render
   * @param {"left" | "right" | "only"} position - The position of the icon relative to text
   * @returns {JSX.Element} The rendered icon element with appropriate styling
   * @private
   */
  const renderIcon = (
    iconName: string,
    position: "left" | "right" | "only",
  ) => {
    const iconStyle =
      position === "left"
        ? { marginRight: "8px" }
        : position === "right"
          ? { marginLeft: "8px" }
          : {};

    const iconSizeClass = getIconSizeClass();

    return (
      <i className={`modus-icons ${iconSizeClass}`} style={iconStyle}>
        {iconName}
      </i>
    );
  };

  /**
   * Determines and renders the button content based on icon position.
   *
   * This function handles the complex logic of combining icons and text content
   * based on the iconPosition prop. It supports three modes:
   * - "left": Icon appears before text
   * - "right": Icon appears after text
   * - "only": Only the icon is displayed (text is hidden)
   *
   * @returns {ReactNode} The rendered content with proper icon and text arrangement
   * @private
   */
  const renderContent = () => {
    if (!icon) {
      return children;
    }

    switch (iconPosition) {
      case "left":
        return (
          <>
            {renderIcon(icon, "left")}
            {children}
          </>
        );
      case "right":
        return (
          <>
            {children}
            {renderIcon(icon, "right")}
          </>
        );
      case "only":
        return renderIcon(icon, "only");
      default:
        return children;
    }
  };

  /**
   * Generates appropriate ARIA label for accessibility.
   *
   * This function ensures proper accessibility by generating ARIA labels
   * for icon-only buttons. If no explicit ariaLabel is provided and the
   * button is icon-only, it uses the text content as the aria-label.
   * This ensures screen readers can properly announce the button's purpose.
   *
   * @returns {string | undefined} The appropriate ARIA label or undefined
   * @private
   */
  const getAriaLabel = () => {
    if (ariaLabel) return ariaLabel;
    if (iconPosition === "only" && typeof children === "string") {
      return children; // Use text content as aria-label for icon-only buttons
    }
    return undefined;
  };

  return (
    <ModusWcButton
      {...(color && { color })}
      {...(variant && { variant })}
      size={size}
      shape={shape}
      disabled={disabled}
      fullWidth={fullWidth}
      pressed={pressed}
      type={type}
      aria-label={getAriaLabel()}
      onButtonClick={onButtonClick}
      custom-class={className}
    >
      {renderContent()}
    </ModusWcButton>
  );
}
