// templates/react/src/components/ModusAvatar.tsx
import { ModusWcAvatar } from "@trimble-oss/moduswebcomponents-react";

/**
 * Props for the ModusAvatar component.
 */
export interface ModusAvatarProps {
  /** The alternative text for the avatar image. */
  alt: string;
  /** The source URL of the avatar image. */
  imgSrc?: string;
  /** Initials displayed when no image source is provided. */
  initials?: string;
  /** The shape of the avatar. */
  shape?: "circle" | "square";
  /** The size of the avatar. */
  size?: "xs" | "sm" | "md" | "lg";
  /** A custom CSS class to apply to the avatar. */
  customClass?: string;
}

/**
 * Renders a Modus avatar component.
 * @param {ModusAvatarProps} props - The component props.
 * @param {string} props.alt - The alternative text for the avatar image.
 * @param {string} [props.imgSrc=""] - The source URL of the avatar image.
 * @param {string} [props.initials=""] - Initials displayed when no image source is provided.
 * @param {'circle' | 'square'} [props.shape='circle'] - The shape of the avatar.
 * @param {'xs' | 'sm' | 'md' | 'lg'} [props.size='md'] - The size of the avatar.
 * @param {string} [props.customClass] - A custom CSS class to apply to the avatar.
 * @returns {JSX.Element} The rendered avatar component.
 */
export default function ModusAvatar({
  alt,
  imgSrc = "",
  initials = "",
  shape = "circle",
  size = "md",
  customClass,
}: ModusAvatarProps) {
  return (
    <ModusWcAvatar
      alt={alt}
      imgSrc={imgSrc}
      initials={initials}
      shape={shape}
      size={size}
      customClass={customClass}
    />
  );
}

// templates/angular/src/app/components/modus-avatar.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcAvatar } from '@trimble-oss/moduswebcomponents-angular';
import type { Components, DaisySize } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusAvatarComponent}.
 */
export interface ModusAvatarProps {
  /** Accessible description for the avatar image or initials. */
  alt: Components.ModusWcAvatar['alt'];
  /** Optional CSS class applied to the host element. */
  className?: Components.ModusWcAvatar['customClass'];
  /** Optional image source displayed inside the avatar. */
  imgSrc?: Components.ModusWcAvatar['imgSrc'];
  /** Initials displayed when no image source is provided. */
  initials?: Components.ModusWcAvatar['initials'];
  /** Shape of the avatar container. */
  shape?: Components.ModusWcAvatar['shape'];
  /** Size token applied to the avatar. */
  size?: DaisySize;
}

/**
 * Angular wrapper for the Modus avatar web component.
 *
 * The avatar supports projecting arbitrary content and can display an image or initials.
 * Use the `shape` and `size` inputs to control the appearance.
 *
 * @example
 * ```html
 * <modus-avatar
 *   alt="Ada Lovelace"
 *   imgSrc="/assets/ada.png"
 *   shape="circle"
 *   size="lg"
 * />
 * ```
 */
@Component({
  selector: 'modus-avatar',
  imports: [CommonModule, ModusWcAvatar],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-avatar
      [alt]="alt()"
      [customClass]="className()"
      [imgSrc]="imgSrc()"
      [initials]="initials()"
      [shape]="shape()"
      [size]="size()"
    >
      <ng-content />
    </modus-wc-avatar>
  `,
})
export class ModusAvatarComponent {
  /** Accessible description for the avatar image or initials. */
  readonly alt = input.required<string>();

  /** Optional CSS class applied to the host element. */
  readonly className = input<string | undefined>();

  /** Optional image source displayed inside the avatar. */
  readonly imgSrc = input<string>('');

  /** Initials displayed when no image source is provided. */
  readonly initials = input<string>('');

  /** Shape of the avatar container. */
  readonly shape = input<'circle' | 'square'>('circle');

  /** Size token applied to the avatar. */
  readonly size = input<DaisySize>('md');
}
