// templates/solidjs/src/components/ModusCheckbox.tsx
import { createEffect } from "solid-js";
import type { Component } from "solid-js";

/**
 * Props for the ModusCheckbox component.
 */
export interface ModusCheckboxProps {
  /** The value of the checkbox. */
  value?: boolean;
  /** Whether the checkbox is disabled. */
  disabled?: boolean;
  /** Whether the checkbox is in an indeterminate state. */
  indeterminate?: boolean;
  /** The label for the checkbox. */
  label?: string;
  /** The name of the checkbox. */
  name?: string;
  /** Whether the checkbox is required. */
  required?: boolean;
  /** The size of the checkbox. */
  size?: "sm" | "md" | "lg";
  /** The ID of the input element. */
  inputId?: string;
  /** The tab index of the input element. */
  inputTabIndex?: number;
  /** A custom CSS class to apply to the checkbox. */
  customClass?: string;
  /** The ARIA label for the checkbox. */
  "aria-label"?: string;
  /** A callback function to handle input changes. */
  onInputChange?: (event: CustomEvent<InputEvent>) => void;
  /** A callback function to handle input focus. */
  onInputFocus?: (event: CustomEvent<FocusEvent>) => void;
  /** A callback function to handle input blur. */
  onInputBlur?: (event: CustomEvent<FocusEvent>) => void;
  /** A callback function to handle value changes. */
  onValueChange?: (event: CustomEvent<boolean>) => void;
}

/**
 * Renders a Modus checkbox component with critical bug workaround.
 *
 * IMPORTANT: This component includes a workaround for a critical value inversion bug
 * in the underlying ModusWcCheckbox web component. The value property returns the
 * opposite of the actual checked state, which is automatically corrected.
 *
 * @example
 * // Basic checkbox
 * <ModusCheckbox label="Accept terms" />
 *
 * @example
 * // Controlled checkbox with value change handler
 * <ModusCheckbox
 *   label="Subscribe to newsletter"
 *   value={isSubscribed()}
 *   onValueChange={(event) => setSubscribed(event.detail)}
 * />
 *
 * @param props - The component props.
 * @returns The rendered checkbox component.
 * @see {@link https://modus.trimble.com/components/checkbox} - Modus Checkbox documentation
 */
const ModusCheckbox: Component<ModusCheckboxProps> = (props) => {
  let checkboxEl: HTMLModusWcCheckboxElement | undefined;

  createEffect(() => {
    const checkbox = checkboxEl;
    if (!checkbox) return;

    const handleInputChange = (event: Event) => {
      props.onInputChange?.(event as CustomEvent<InputEvent>);
    };
    const handleInputFocus = (event: Event) => {
      props.onInputFocus?.(event as CustomEvent<FocusEvent>);
    };
    const handleInputBlur = (event: Event) => {
      props.onInputBlur?.(event as CustomEvent<FocusEvent>);
    };
    const handleValueChange = (event: Event) => {
      const customEvent = event as CustomEvent<InputEvent>;
      const rawValue = (customEvent.target as HTMLModusWcCheckboxElement).value;
      const actualValue = !rawValue;
      const correctedEvent = new CustomEvent("valueChange", {
        detail: actualValue,
        bubbles: true,
        cancelable: true,
      });
      props.onValueChange?.(correctedEvent);
    };

    if (props.onInputChange)
      checkbox.addEventListener("inputChange", handleInputChange);
    if (props.onInputFocus)
      checkbox.addEventListener("inputFocus", handleInputFocus);
    if (props.onInputBlur)
      checkbox.addEventListener("inputBlur", handleInputBlur);
    if (props.onValueChange)
      checkbox.addEventListener("inputChange", handleValueChange);

    return () => {
      if (props.onInputChange)
        checkbox.removeEventListener("inputChange", handleInputChange);
      if (props.onInputFocus)
        checkbox.removeEventListener("inputFocus", handleInputFocus);
      if (props.onInputBlur)
        checkbox.removeEventListener("inputBlur", handleInputBlur);
      if (props.onValueChange)
        checkbox.removeEventListener("inputChange", handleValueChange);
    };
  });

  return (
    <modus-wc-checkbox
      ref={(el) => (checkboxEl = el)}
      value={props.value ?? false}
      disabled={props.disabled ?? false}
      indeterminate={props.indeterminate ?? false}
      label={props.label}
      name={props.name ?? ""}
      required={props.required ?? false}
      size={props.size ?? "md"}
      input-id={props.inputId}
      input-tab-index={props.inputTabIndex}
      custom-class={props.customClass}
      aria-label={props["aria-label"]}
    />
  );
};

export default ModusCheckbox;

// templates/angular/src/app/components/modus-checkbox.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcCheckbox } from '@trimble-oss/moduswebcomponents-angular';
import type { Components, ModusSize } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusCheckboxComponent}.
 */
export interface ModusCheckboxProps {
  /** Custom CSS class applied to the checkbox input. */
  className?: Components.ModusWcCheckbox['customClass'];
  /** Whether the checkbox is disabled. */
  disabled?: Components.ModusWcCheckbox['disabled'];
  /** Indeterminate visual state for tri-state checkboxes. */
  indeterminate?: Components.ModusWcCheckbox['indeterminate'];
  /** Identifier applied to the checkbox input element. */
  inputId?: Components.ModusWcCheckbox['inputId'];
  /** Tab index applied to the checkbox input. */
  inputTabIndex?: Components.ModusWcCheckbox['inputTabIndex'];
  /** Optional label rendered alongside the checkbox. */
  label?: Components.ModusWcCheckbox['label'];
  /** Name attribute submitted in form payloads. */
  name?: Components.ModusWcCheckbox['name'];
  /** Marks the checkbox as required. */
  required?: Components.ModusWcCheckbox['required'];
  /** Size token controlling checkbox dimensions. */
  size?: ModusSize;
  /** Bound value indicating whether the checkbox is selected. */
  value?: Components.ModusWcCheckbox['value'];
}

/**
 * Angular wrapper for the Modus checkbox web component.
 *
 * @example
 * ```html
 * <modus-checkbox
 *   label="Accept terms"
 *   [value]="acceptTerms()"
 *   (valueChange)="acceptTerms.set($event)"
 * />
 * ```
 */
@Component({
  selector: 'modus-checkbox',
  imports: [CommonModule, ModusWcCheckbox],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-checkbox
      [customClass]="className()"
      [disabled]="disabled()"
      [indeterminate]="indeterminate()"
      [inputId]="inputId()"
      [inputTabIndex]="inputTabIndex()"
      [label]="label()"
      [name]="name()"
      [required]="required()"
      [size]="size()"
      [value]="value()"
      (inputBlur)="handleBlur($event)"
      (inputChange)="handleChange($event)"
      (inputFocus)="handleFocus($event)"
    />
  `,
})
export class ModusCheckboxComponent {
  /** Custom CSS class applied to the checkbox input. */
  readonly className = input<string | undefined>();

  /** Whether the checkbox is disabled. */
  readonly disabled = input<boolean | undefined>(false);

  /** Indeterminate visual state for tri-state checkboxes. */
  readonly indeterminate = input<boolean | undefined>(false);

  /** Identifier applied to the checkbox input element. */
  readonly inputId = input<string | undefined>();

  /** Tab index applied to the checkbox input. */
  readonly inputTabIndex = input<number | undefined>();

  /** Optional label rendered alongside the checkbox. */
  readonly label = input<string | undefined>();

  /** Name attribute submitted in form payloads. */
  readonly name = input<string | undefined>('');

  /** Marks the checkbox as required. */
  readonly required = input<boolean | undefined>(false);

  /** Size token controlling checkbox dimensions. */
  readonly size = input<ModusSize | undefined>('md');

  /** Bound value indicating whether the checkbox is selected. */
  readonly value = input<boolean | undefined>(false);

  /** Emits when the checkbox loses focus. */
  readonly inputBlur = output<FocusEvent>();

  /** Emits when the checkbox value changes. */
  readonly inputChange = output<InputEvent>();

  /** Emits when the checkbox gains focus. */
  readonly inputFocus = output<FocusEvent>();

  handleBlur(event: CustomEvent<FocusEvent>): void {
    this.inputBlur.emit(event.detail);
  }

  handleChange(event: CustomEvent<InputEvent>): void {
    this.inputChange.emit(event.detail);
  }

  handleFocus(event: CustomEvent<FocusEvent>): void {
    this.inputFocus.emit(event.detail);
  }
}
