// templates/react/src/components/ModusButtonGroup.tsx
import { ModusWcButtonGroup } from "@trimble-oss/moduswebcomponents-react";
import type { ReactNode } from "react";

/**
 * Props for the ModusButtonGroup component.
 */
export interface ModusButtonGroupProps {
  /** The content to display inside the button group (ModusButton components). */
  children?: ReactNode;
  /** Style variant applied to all buttons within the group. */
  variant?: "borderless" | "filled" | "outlined";
  /** Color applied to all buttons within the group. */
  color?: "primary" | "secondary" | "tertiary" | "warning" | "danger";
  /** Disables all buttons within the button group. */
  disabled?: boolean;
  /** Orientation of the button group: horizontal or vertical. */
  orientation?: "horizontal" | "vertical";
  /** Selection behavior - default (no selection), single (radio-like), or multiple (checkbox-like). */
  selectionType?: "default" | "single" | "multiple";
  /** Callback when any button in the group is clicked. */
  onButtonGroupClick?: (
    event: CustomEvent<{ button: HTMLElement; isSelected: boolean }>,
  ) => void;
  /** Callback when button selection changes. */
  onButtonSelectionChange?: (
    event: CustomEvent<{ selectedButtons: HTMLElement[] }>,
  ) => void;
  /** A custom CSS class to apply to the button group. */
  customClass?: string;
  /** The ARIA label for the button group. */
  ariaLabel?: string;
}

/**
 * Renders a Modus button group component that groups multiple buttons together.
 *
 * @example
 * // Basic horizontal button group
 * <ModusButtonGroup variant="outlined" color="primary">
 *   <ModusButton>Button 1</ModusButton>
 *   <ModusButton>Button 2</ModusButton>
 *   <ModusButton>Button 3</ModusButton>
 * </ModusButtonGroup>
 *
 * @example
 * // Single selection (radio-like behavior)
 * <ModusButtonGroup selectionType="single" variant="outlined">
 *   <ModusButton>Option 1</ModusButton>
 *   <ModusButton pressed>Option 2</ModusButton>
 *   <ModusButton>Option 3</ModusButton>
 * </ModusButtonGroup>
 *
 * @example
 * // Multiple selection (checkbox-like behavior)
 * <ModusButtonGroup selectionType="multiple" variant="outlined">
 *   <ModusButton pressed>Bold</ModusButton>
 *   <ModusButton>Italic</ModusButton>
 *   <ModusButton pressed>Underline</ModusButton>
 * </ModusButtonGroup>
 *
 * @param {ModusButtonGroupProps} props - The component props.
 * @returns {JSX.Element} The rendered button group component.
 */
export default function ModusButtonGroup({
  children,
  variant = "outlined",
  color,
  disabled = false,
  orientation = "horizontal",
  selectionType = "default",
  onButtonGroupClick,
  onButtonSelectionChange,
  customClass,
  ariaLabel,
}: ModusButtonGroupProps) {
  return (
    <ModusWcButtonGroup
      variant={variant}
      color={color}
      disabled={disabled}
      orientation={orientation}
      selection-type={selectionType}
      onButtonGroupClick={onButtonGroupClick}
      onButtonSelectionChange={onButtonSelectionChange}
      custom-class={customClass}
      aria-label={ariaLabel}
    >
      {children}
    </ModusWcButtonGroup>
  );
}

// templates/angular/src/app/components/modus-button-group.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcButtonGroup } from '@trimble-oss/moduswebcomponents-angular';
import type { Components } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusButtonGroupComponent}.
 */
export interface ModusButtonGroupProps {
  /** Variant applied to all buttons within the group. */
  variant?: Components.ModusWcButtonGroup['variant'];
  /** Color applied to all buttons within the group. */
  color?: Components.ModusWcButtonGroup['color'];
  /** Disable all buttons within the group. */
  disabled?: Components.ModusWcButtonGroup['disabled'];
  /** Layout orientation for the group. */
  orientation?: Components.ModusWcButtonGroup['orientation'];
  /** Selection behavior for the group. */
  selectionType?: Components.ModusWcButtonGroup['selectionType'];
  /** Accessible label for the group. */
  ariaLabel?: string;
}

/**
 * Angular wrapper for the Modus button group web component.
 */
@Component({
  selector: 'modus-button-group',
  imports: [CommonModule, ModusWcButtonGroup],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-button-group
      [variant]="variant()"
      [color]="color()"
      [disabled]="disabled()"
      [orientation]="orientation()"
      [selectionType]="selectionType()"
      [attr.aria-label]="ariaLabel()"
      (buttonGroupClick)="handleButtonGroupClick($event)"
      (buttonSelectionChange)="handleButtonSelectionChange($event)"
    >
      <ng-content />
    </modus-wc-button-group>
  `,
})
export class ModusButtonGroupComponent {
  /** Variant applied to all buttons within the group. */
  readonly variant = input<Components.ModusWcButtonGroup['variant'] | undefined>('outlined');

  /** Color applied to all buttons within the group. */
  readonly color = input<Components.ModusWcButtonGroup['color'] | undefined>();

  /** Disable all buttons within the group. */
  readonly disabled = input<Components.ModusWcButtonGroup['disabled'] | undefined>(false);

  /** Layout orientation for the group. */
  readonly orientation = input<Components.ModusWcButtonGroup['orientation'] | undefined>('horizontal');

  /** Selection behavior for the group. */
  readonly selectionType = input<Components.ModusWcButtonGroup['selectionType'] | undefined>('default');

  /** Accessible label for the group. */
  readonly ariaLabel = input<string | undefined>();

  /** Emits when a button in the group is clicked. */
  readonly buttonGroupClick = output<{ button: HTMLElement; isSelected: boolean }>();

  /** Emits when the group selection changes. */
  readonly buttonSelectionChange = output<{ selectedButtons: HTMLElement[] }>();

  handleButtonGroupClick(
    event: CustomEvent<{ button: HTMLElement; isSelected: boolean }>,
  ): void {
    this.buttonGroupClick.emit(event.detail);
  }

  handleButtonSelectionChange(
    event: CustomEvent<{ selectedButtons: HTMLElement[] }>,
  ): void {
    this.buttonSelectionChange.emit(event.detail);
  }
}
