// templates/solidjs/src/components/ModusSkeleton.tsx
import type { Component } from "solid-js";

type SkeletonShape = "circle" | "rectangle";

/**
 * Props for the ModusSkeleton component.
 */
export interface ModusSkeletonProps {
  height?: string;
  width?: string;
  shape?: SkeletonShape;
  customClass?: string;
  ariaLabel?: string;
}

/**
 * Renders a Modus skeleton component.
 * @param {ModusSkeletonProps} props - The component props.
 * @returns {JSX.Element} The rendered skeleton component.
 */
const ModusSkeleton: Component<ModusSkeletonProps> = (props) => {
  return (
    <modus-wc-skeleton
      height={props.height ?? "var(--modus-wc-line-height-md)"}
      width={props.width ?? "100%"}
      shape={props.shape ?? "rectangle"}
      custom-class={props.customClass}
      aria-label={props.ariaLabel ?? "Loading placeholder"}
    />
  );
};

export default ModusSkeleton;

// templates/angular/src/app/components/modus-skeleton.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcSkeleton } from '@trimble-oss/moduswebcomponents-angular';
import type { Components } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusSkeletonComponent}.
 */
export interface ModusSkeletonProps {
  /** Custom CSS class applied to the skeleton element. */
  className?: Components.ModusWcSkeleton['customClass'];
  /** The height of the skeleton. */
  height?: Components.ModusWcSkeleton['height'];
  /** The shape of the skeleton. */
  shape?: Components.ModusWcSkeleton['shape'];
  /** The width of the skeleton. */
  width?: Components.ModusWcSkeleton['width'];
}

/**
 * Angular wrapper for the Modus skeleton web component.
 *
 * @example
 * ```html
 * <modus-skeleton shape="rectangle" width="200px" height="20px" />
 * ```
 */
@Component({
  selector: 'modus-skeleton',
  imports: [CommonModule, ModusWcSkeleton],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-skeleton
      [customClass]="className()"
      [height]="height()"
      [shape]="shape()"
      [width]="width()"
    />
  `,
})
export class ModusSkeletonComponent {
  /** Custom CSS class applied to the skeleton element. */
  readonly className = input<string | undefined>();

  /** The height of the skeleton. */
  readonly height = input<string>('var(--modus-wc-line-height-md)');

  /** The shape of the skeleton. */
  readonly shape = input<'circle' | 'rectangle' | undefined>('rectangle');

  /** The width of the skeleton. */
  readonly width = input<string>('100%');
}
