// templates/solidjs/src/components/ModusFileDropzone.tsx
import { onMount, Show, type Component } from "solid-js";
import type { JSX } from "solid-js";

/**
 * Props for the ModusFileDropzone component.
 */
export interface ModusFileDropzoneProps {
  /** Accepted file types (e.g., '.jpg,.png' or 'image/*'). */
  acceptFileTypes?: string;
  /** Custom CSS class to apply to the dropzone element. */
  customClass?: string;
  /** Disables the file input and dropzone interaction. */
  disabled?: boolean;
  /** Custom instructions shown when files are dragged over the dropzone. */
  fileDraggedOverInstructions?: string;
  /** Show state icon (upload, success, error) in the dropzone. */
  includeStateIcon?: boolean;
  /** Custom instructions shown as the default dropzone message. */
  instructions?: string;
  /** Custom error message when an invalid file type is selected. */
  invalidFileTypeMessage?: string;
  /** Maximum number of files allowed; shows error if exceeded. */
  maxFileCount?: number;
  /** Maximum allowed length of filename (excluding extension); shows error if exceeded. */
  maxFileNameLength?: number;
  /** Maximum total file size in bytes; shows error if exceeded. */
  maxTotalFileSizeBytes?: number;
  /** Allow multiple file selection. */
  multiple?: boolean;
  /** Success message displayed when files are uploaded successfully. */
  successMessage?: string;
  /** Callback when files are selected (via drag-and-drop or file browser). */
  onFileSelect?: (event: CustomEvent<FileList>) => void;
  /** The ARIA label for the dropzone. */
  ariaLabel?: string;
  /** Custom content slot for progress indicators or additional instructions. */
  children?: JSX.Element;
  /** Callback to receive ref handle for programmatic reset. */
  ref?: (handle: ModusFileDropzoneHandle) => void;
}

/**
 * Handle interface for ModusFileDropzone ref methods.
 */
export interface ModusFileDropzoneHandle {
  /** Resets the dropzone to its initial state, clearing all error and success states. */
  reset: () => Promise<void>;
}

/**
 * Renders a Modus file dropzone component for drag-and-drop file uploads.
 *
 * @example
 * // Basic file dropzone
 * <ModusFileDropzone
 *   acceptFileTypes=".doc, .docx, .pdf"
 *   instructions="Drag files here or browse to upload"
 * />
 *
 * @example
 * // Multiple files with validation
 * <ModusFileDropzone
 *   acceptFileTypes="image/*"
 *   multiple
 *   maxFileCount={3}
 *   maxTotalFileSizeBytes={10485760}
 *   instructions="Upload images (max 3 files, 10MB total)"
 *   onFileSelect={(e) => console.log('Files:', e.detail)}
 * />
 *
 * @example
 * // With ref for programmatic reset
 * let dropzoneHandle: ModusFileDropzoneHandle | undefined;
 * <ModusFileDropzone ref={(h) => dropzoneHandle = h} />
 * // Later: dropzoneHandle?.reset();
 *
 * @param {ModusFileDropzoneProps} props - The component props.
 * @returns {JSX.Element} The rendered file dropzone component.
 */
const ModusFileDropzone: Component<ModusFileDropzoneProps> = (props) => {
  let dropzoneEl: (HTMLElement & { reset?: () => Promise<void> }) | undefined;

  onMount(() => {
    props.ref?.({
      reset: async () => {
        if (dropzoneEl?.reset) {
          await dropzoneEl.reset();
        }
      },
    });
  });

  return (
    <modus-wc-file-dropzone
      ref={(el) => (dropzoneEl = el as HTMLElement & { reset?: () => Promise<void> })}
      accept-file-types={props.acceptFileTypes}
      custom-class={props.customClass}
      disabled={props.disabled}
      file-dragged-over-instructions={props.fileDraggedOverInstructions}
      include-state-icon={props.includeStateIcon ?? true}
      instructions={props.instructions}
      invalid-file-type-message={props.invalidFileTypeMessage}
      max-file-count={props.maxFileCount}
      max-file-name-length={props.maxFileNameLength}
      max-total-file-size-bytes={props.maxTotalFileSizeBytes}
      multiple={props.multiple}
      success-message={props.successMessage}
      aria-label={props.ariaLabel}
      on:fileSelect={(e: CustomEvent<FileList>) => props.onFileSelect?.(e)}
    >
      <Show when={props.children}>
        <div slot="dropzone">{props.children}</div>
      </Show>
    </modus-wc-file-dropzone>
  );
};

export default ModusFileDropzone;

// templates/angular/src/app/components/modus-file-dropzone.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, ViewChild, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcFileDropzone } from '@trimble-oss/moduswebcomponents-angular';
import type { Components } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusFileDropzoneComponent}.
 */
export interface ModusFileDropzoneProps {
  /** Accepted file types (e.g. `.jpg,.png`). */
  acceptFileTypes?: Components.ModusWcFileDropzone['acceptFileTypes'];
  /** Optional CSS class applied to the dropzone. */
  className?: Components.ModusWcFileDropzone['customClass'];
  /** Disables the dropzone interaction. */
  disabled?: Components.ModusWcFileDropzone['disabled'];
  /** Instructions displayed while dragging files. */
  fileDraggedOverInstructions?: Components.ModusWcFileDropzone['fileDraggedOverInstructions'];
  /** Shows contextual icons for upload, success, and error states. */
  includeStateIcon?: Components.ModusWcFileDropzone['includeStateIcon'];
  /** Default instructions displayed in the dropzone. */
  instructions?: Components.ModusWcFileDropzone['instructions'];
  /** Error message shown for invalid file type. */
  invalidFileTypeMessage?: Components.ModusWcFileDropzone['invalidFileTypeMessage'];
  /** Maximum number of files allowed. */
  maxFileCount?: Components.ModusWcFileDropzone['maxFileCount'];
  /** Maximum file name length. */
  maxFileNameLength?: Components.ModusWcFileDropzone['maxFileNameLength'];
  /** Maximum total file size in bytes. */
  maxTotalFileSizeBytes?: Components.ModusWcFileDropzone['maxTotalFileSizeBytes'];
  /** Allow multiple file selection. */
  multiple?: Components.ModusWcFileDropzone['multiple'];
  /** Success message shown after valid upload. */
  successMessage?: Components.ModusWcFileDropzone['successMessage'];
}

/**
 * Angular wrapper for the Modus file dropzone web component.
 */
@Component({
  selector: 'modus-file-dropzone',
  imports: [CommonModule, ModusWcFileDropzone],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-file-dropzone
      [acceptFileTypes]="acceptFileTypes()"
      [customClass]="className()"
      [disabled]="disabled()"
      [fileDraggedOverInstructions]="fileDraggedOverInstructions()"
      [includeStateIcon]="includeStateIcon()"
      [instructions]="instructions()"
      [invalidFileTypeMessage]="invalidFileTypeMessage()"
      [maxFileCount]="maxFileCount()"
      [maxFileNameLength]="maxFileNameLength()"
      [maxTotalFileSizeBytes]="maxTotalFileSizeBytes()"
      [multiple]="multiple()"
      [successMessage]="successMessage()"
      (fileSelect)="handleFileSelect($event)"
    >
      <ng-content select="[slot='dropzone']" slot="dropzone" />
    </modus-wc-file-dropzone>
  `,
})
export class ModusFileDropzoneComponent {
  @ViewChild(ModusWcFileDropzone, { read: ElementRef })
  private readonly dropzoneElement?: ElementRef<HTMLElement>;

  /** Accepted file types (e.g. `.jpg,.png`). */
  readonly acceptFileTypes = input<string | undefined>();

  /** Optional CSS class applied to the dropzone. */
  readonly className = input<string | undefined>();

  /** Disables the dropzone interaction. */
  readonly disabled = input<boolean | undefined>(false);

  /** Instructions displayed while dragging files. */
  readonly fileDraggedOverInstructions = input<string | undefined>();

  /** Shows contextual icons for upload, success, and error states. */
  readonly includeStateIcon = input<boolean | undefined>(true);

  /** Default instructions displayed in the dropzone. */
  readonly instructions = input<string | undefined>();

  /** Error message shown for invalid file type. */
  readonly invalidFileTypeMessage = input<string | undefined>();

  /** Maximum number of files allowed. */
  readonly maxFileCount = input<number | undefined>();

  /** Maximum file name length. */
  readonly maxFileNameLength = input<number | undefined>();

  /** Maximum total file size in bytes. */
  readonly maxTotalFileSizeBytes = input<number | undefined>();

  /** Allow multiple file selection. */
  readonly multiple = input<boolean | undefined>(false);

  /** Success message shown after valid upload. */
  readonly successMessage = input<string | undefined>();

  /** Emits selected files when the user drops or chooses files. */
  readonly fileSelect = output<FileList>();

  /**
   * Resets the dropzone to its initial state.
   */
  async reset(): Promise<void> {
    const element = this.dropzoneElement?.nativeElement as
      | (HTMLElement & { reset?: () => Promise<void> })
      | undefined;
    if (element?.reset) {
      await element.reset();
    }
  }

  handleFileSelect(event: CustomEvent<FileList>): void {
    this.fileSelect.emit(event.detail);
  }
}
