// templates/react/src/demos/pagination-demo/page.tsx
"use client";

import { useState } from "react";
import DemoExample from "../../components/DemoExample";
import DemoPage from "../../components/DemoPage";
import ModusPagination from "../../components/ModusPagination";

export default function PaginationDemoPage() {
  const [paginationState, setPaginationState] = useState({
    page: 2,
    count: 8,
  });

  const handlePageChange = (
    event: CustomEvent<{ newPage: number; prevPage: number }>,
  ) => {
    setPaginationState((state) => ({
      ...state,
      page: event.detail.newPage,
    }));
  };

  return (
    <DemoPage
      title="Modus Pagination"
      description="Pagination components enable users to navigate through multiple pages of content. Use pagination for tables, lists, or any paginated content."
    >
      <DemoExample
        title="Basic Pagination"
        description="Simple pagination with page count and current page."
      >
        <div className="flex flex-col gap-6">
          <ModusPagination count={8} page={1} ariaLabel="Basic pagination 1" />
          <ModusPagination count={5} page={3} ariaLabel="Basic pagination 2" />
          <ModusPagination count={10} page={5} ariaLabel="Basic pagination 3" />
        </div>
      </DemoExample>

      <DemoExample
        title="Pagination Sizes"
        description="Pagination in different sizes."
      >
        <div className="flex flex-col gap-6">
          <div className="flex flex-col gap-2">
            <div className="text-sm text-muted-foreground">Small</div>
            <ModusPagination
              count={5}
              page={2}
              size="sm"
              ariaLabel="Small pagination"
            />
          </div>

          <div className="flex flex-col gap-2">
            <div className="text-sm text-muted-foreground">
              Medium (Default)
            </div>
            <ModusPagination
              count={5}
              page={2}
              size="md"
              ariaLabel="Medium pagination"
            />
          </div>

          <div className="flex flex-col gap-2">
            <div className="text-sm text-muted-foreground">Large</div>
            <ModusPagination
              count={5}
              page={2}
              size="lg"
              ariaLabel="Large pagination"
            />
          </div>
        </div>
      </DemoExample>

      <DemoExample
        title="Custom Button Text"
        description="Pagination with custom previous and next button text."
      >
        <div className="flex flex-col gap-6">
          <ModusPagination
            count={5}
            page={2}
            prevButtonText="Previous"
            nextButtonText="Next"
            ariaLabel="Pagination with text labels"
          />
          <ModusPagination
            count={5}
            page={3}
            prevButtonText="←"
            nextButtonText="→"
            ariaLabel="Pagination with arrow labels"
          />
        </div>
      </DemoExample>

      <DemoExample
        title="Interactive Pagination"
        description="Pagination with state management and event handling."
      >
        <div className="flex flex-col gap-6">
          <ModusPagination
            count={paginationState.count}
            page={paginationState.page}
            onPageChange={handlePageChange}
            ariaLabel="Interactive pagination"
          />
          <div className="p-4 rounded-lg bg-card border border-default">
            <div className="text-sm text-foreground">
              <strong>Current Page:</strong> {paginationState.page} /{" "}
              {paginationState.count}
            </div>
            <div className="text-sm text-muted-foreground mt-2">
              Click the pagination controls above to navigate between pages.
            </div>
          </div>
        </div>
      </DemoExample>

      <DemoExample
        title="Real-World Example"
        description="Pagination integrated with content display."
      >
        <div className="flex flex-col gap-6">
          <div className="p-4 rounded-lg bg-card border border-default">
            <div className="text-sm text-foreground mb-2">
              Showing page {paginationState.page} of {paginationState.count}
            </div>
            <div className="text-sm text-muted-foreground">
              Items {(paginationState.page - 1) * 10 + 1}-
              {paginationState.page * 10} of {paginationState.count * 10}
            </div>
          </div>
          <ModusPagination
            count={paginationState.count}
            page={paginationState.page}
            onPageChange={handlePageChange}
            ariaLabel="Real-world pagination example"
          />
        </div>
      </DemoExample>
    </DemoPage>
  );
}

// templates/angular/src/app/demos/pagination/pagination-demo.component.ts
import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DemoPageComponent } from '../shared/demo-page.component';
import { DemoExampleComponent } from '../shared/demo-example.component';
import { ModusPaginationComponent } from '../../components/modus-pagination.component';
import type { IPageChange } from '@trimble-oss/moduswebcomponents';

/**
 * Demo page showcasing the Modus Pagination component.
 *
 * Demonstrates pagination features including:
 * - Basic pagination
 * - Different sizes
 * - Custom button text
 * - Interactive pagination
 */
@Component({
  selector: 'app-pagination-demo-page',
  standalone: true,
  imports: [CommonModule, DemoPageComponent, DemoExampleComponent, ModusPaginationComponent],
  template: `
    <demo-page
      title="Modus Pagination"
      description="Pagination components enable users to navigate through multiple pages of content. Use pagination for tables, lists, or any paginated content."
    >
      <demo-example
        title="Basic Pagination"
        description="Simple pagination with page count and current page."
      >
        <div class="flex flex-col gap-6">
          <modus-pagination [count]="8" [page]="1" />
          <modus-pagination [count]="5" [page]="3" />
          <modus-pagination [count]="10" [page]="5" />
        </div>
      </demo-example>

      <demo-example
        title="Pagination Sizes"
        description="Pagination in different sizes."
      >
        <div class="flex flex-col gap-6">
          <div class="flex flex-col gap-2">
            <p class="text-sm text-muted-foreground">Small</p>
            <modus-pagination [count]="5" [page]="2" size="sm" />
          </div>

          <div class="flex flex-col gap-2">
            <p class="text-sm text-muted-foreground">Medium (Default)</p>
            <modus-pagination [count]="5" [page]="2" size="md" />
          </div>

          <div class="flex flex-col gap-2">
            <p class="text-sm text-muted-foreground">Large</p>
            <modus-pagination [count]="5" [page]="2" size="lg" />
          </div>
        </div>
      </demo-example>

      <demo-example
        title="Custom Button Text"
        description="Pagination with custom previous and next button text."
      >
        <div class="flex flex-col gap-6">
          <modus-pagination
            [count]="5"
            [page]="2"
            prevButtonText="Previous"
            nextButtonText="Next"
          />
          <modus-pagination
            [count]="5"
            [page]="3"
            prevButtonText="←"
            nextButtonText="→"
          />
        </div>
      </demo-example>

      <demo-example
        title="Interactive Pagination"
        description="Pagination with two-way binding and event handling."
      >
        <div class="flex flex-col gap-6">
          <modus-pagination
            [count]="paginationState().count"
            [page]="paginationState().page"
            (pageChange)="handlePageChange($event)"
          />
          <div class="p-4 rounded-lg bg-card border-default">
            <p class="text-sm text-foreground">
              <strong>Current Page:</strong> {{ paginationState().page }} / {{ paginationState().count }}
            </p>
            <p class="text-sm text-muted-foreground mt-2">
              Click the pagination controls above to navigate between pages.
            </p>
          </div>
        </div>
      </demo-example>

      <demo-example
        title="Real-World Example"
        description="Pagination integrated with content display."
      >
        <div class="flex flex-col gap-6">
          <div class="p-4 rounded-lg bg-card border-default">
            <p class="text-sm text-foreground mb-2">
              Showing page {{ paginationState().page }} of {{ paginationState().count }}
            </p>
            <p class="text-sm text-muted-foreground">
              Items {{ (paginationState().page - 1) * 10 + 1 }}-{{ paginationState().page * 10 }} of
              {{ paginationState().count * 10 }}
            </p>
          </div>
          <modus-pagination
            [count]="paginationState().count"
            [page]="paginationState().page"
            (pageChange)="handlePageChange($event)"
          />
        </div>
      </demo-example>
    </demo-page>
  `,
})
export class PaginationDemoPageComponent {
  readonly paginationState = signal<{ page: number; count: number }>({ page: 2, count: 8 });

  handlePageChange(change: IPageChange): void {
    this.paginationState.update((state) => ({
      ...state,
      page: change.newPage,
    }));
  }
}
