// templates/angular/src/app/components/modus-modal.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcModal } from '@trimble-oss/moduswebcomponents-angular';
import type { Components } from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusModalComponent}.
 */
export interface ModusModalProps {
  /** Modal backdrop behavior. */
  backdrop?: Components.ModusWcModal['backdrop'];
  /** Custom CSS class applied to the modal container. */
  className?: Components.ModusWcModal['customClass'];
  /** Renders the modal fullscreen. */
  fullscreen?: Components.ModusWcModal['fullscreen'];
  /** Required identifier applied to the underlying dialog element. */
  modalId: Components.ModusWcModal['modalId'];
  /** Vertical positioning of the modal. */
  position?: Components.ModusWcModal['position'];
  /** Toggles the close button in the header. */
  showClose?: Components.ModusWcModal['showClose'];
  /** Toggles the fullscreen icon button. */
  showFullscreenToggle?: Components.ModusWcModal['showFullscreenToggle'];
}

/**
 * Angular wrapper for the Modus modal web component.
 */
@Component({
  selector: 'modus-modal',
  imports: [CommonModule, ModusWcModal],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-modal
      [backdrop]="backdrop()"
      [customClass]="className()"
      [fullscreen]="fullscreen()"
      [modalId]="modalId()"
      [position]="position()"
      [showClose]="showClose()"
      [showFullscreenToggle]="showFullscreenToggle()"
    >
      <ng-content select="[slot='header']" slot="header" />
      <ng-content select="[slot='content']" slot="content" />
      <ng-content select="[slot='footer']" slot="footer" />
    </modus-wc-modal>
  `,
})
export class ModusModalComponent {
  /** Modal backdrop behavior. */
  readonly backdrop = input<'default' | 'static' | undefined>('default');

  /** Custom CSS class applied to the modal container. */
  readonly className = input<string | undefined>();

  /** Renders the modal fullscreen. */
  readonly fullscreen = input<boolean | undefined>(false);

  /** Required identifier applied to the underlying dialog element. */
  readonly modalId = input.required<string>();

  /** Vertical positioning of the modal. */
  readonly position = input<'bottom' | 'center' | 'top' | undefined>('center');

  /** Toggles the close button in the header. */
  readonly showClose = input<boolean | undefined>(true);

  /** Toggles the fullscreen icon button. */
  readonly showFullscreenToggle = input<boolean | undefined>(false);
}

// templates/solidjs/src/components/ModusModal.tsx
import { onCleanup, onMount } from "solid-js";
import type { Component, JSX } from "solid-js";

/**
 * Props for the ModusModal component.
 */
interface ModusModalProps {
  /** A unique identifier for the modal. */
  modalId: string;
  /** The ARIA label for the modal. */
  ariaLabel?: string;

  /** The type of backdrop for the modal. */
  backdrop?: "default" | "static";
  /** The position of the modal. */
  position?: "top" | "center" | "bottom";
  /** Whether the modal should be fullscreen. */
  fullscreen?: boolean;
  /** Whether to show the fullscreen toggle button. */
  showFullscreenToggle?: boolean;
  /** Whether to show the close button. */
  showClose?: boolean;
  /** A custom CSS class to apply to the modal. */
  customClass?: string;

  /** The header content of the modal. */
  header?: JSX.Element;
  /** The main content of the modal. */
  children: JSX.Element;
  /** The footer content of the modal. */
  footer?: JSX.Element;

  /** A callback function to handle the close event. */
  onClose?: () => void;

  /** A CSS class to apply to the modal. */
  className?: string;

  /** Callback to receive ref handle for programmatic open/close. */
  ref?: (handle: ModusModalRef) => void;
}

/**
 * A ref object for the ModusModal component.
 */
export interface ModusModalRef {
  /** Opens the modal. */
  openModal: () => void;
  /** Closes the modal. */
  closeModal: () => void;
}

/**
 * Renders a Modus modal component.
 * @param props - The component props.
 * @returns The rendered modal component.
 */
const ModusModal: Component<ModusModalProps> = (props) => {
  let modalEl: HTMLModusWcModalElement | undefined;

  const openModal = () => {
    if (modalEl) {
      const dialog = modalEl.querySelector("dialog") as HTMLDialogElement;
      if (dialog) dialog.showModal();
    }
  };

  const closeModal = () => {
    if (modalEl) {
      const dialog = modalEl.querySelector("dialog") as HTMLDialogElement;
      if (dialog) dialog.close();
    }
  };

  onMount(() => {
    props.ref?.({ openModal, closeModal });

    const modal = modalEl;
    if (modal) {
      const handleClose = () => props.onClose?.();
      const dialogElement = modal.querySelector("dialog");
      if (dialogElement) {
        dialogElement.addEventListener("close", handleClose);
        onCleanup(() => {
          dialogElement.removeEventListener("close", handleClose);
        });
      }
    }
  });

  return (
    <modus-wc-modal
      ref={(el) => (modalEl = el)}
      modal-id={props.modalId}
      aria-label={props.ariaLabel}
      backdrop={props.backdrop ?? "default"}
      position={props.position ?? "center"}
      fullscreen={props.fullscreen ?? false}
      show-fullscreen-toggle={props.showFullscreenToggle ?? false}
      show-close={props.showClose ?? true}
      custom-class={props.customClass ?? props.className}
    >
      {props.header && <div slot="header">{props.header}</div>}
      <div slot="content">{props.children}</div>
      {props.footer && <div slot="footer">{props.footer}</div>}
    </modus-wc-modal>
  );
};

export default ModusModal;
