// templates/angular/src/app/components/modus-stepper.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcStepper } from '@trimble-oss/moduswebcomponents-angular';
import type { Components, Orientation } from '@trimble-oss/moduswebcomponents';

/**
 * Props for a step item in the stepper component.
 */
export interface IStepperItem {
  /** The color theme of the step. */
  color?: 'primary' | 'secondary' | 'accent' | 'info' | 'success' | 'warning' | 'error' | 'neutral';
  /** Custom content to display in the step indicator. */
  content?: string;
  /** Custom CSS class to apply to the step. */
  customClass?: string;
  /** Text label for the step. */
  label?: string;
}

/**
 * Props supported by the {@link ModusStepperComponent}.
 */
export interface ModusStepperProps {
  /** Custom CSS class applied to the stepper element. */
  className?: Components.ModusWcStepper['customClass'];
  /** The orientation of the steps. */
  orientation?: Orientation;
  /** The steps to display. */
  steps: IStepperItem[];
}

/**
 * Angular wrapper for the Modus stepper web component.
 *
 * Used to show a list of steps in a process.
 *
 * @example
 * ```html
 * <modus-stepper
 *   [steps]="[
 *     { label: 'Step 1', color: 'primary' },
 *     { label: 'Step 2', color: 'info' },
 *     { label: 'Step 3' }
 *   ]"
 * />
 * ```
 */
@Component({
  selector: 'modus-stepper',
  imports: [CommonModule, ModusWcStepper],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-stepper [customClass]="className()" [orientation]="orientation()" [steps]="steps()" />
  `,
})
export class ModusStepperComponent {
  /** Custom CSS class applied to the stepper element. */
  readonly className = input<string | undefined>();

  /** The orientation of the steps. */
  readonly orientation = input<Orientation | undefined>();

  /** The steps to display. */
  readonly steps = input.required<IStepperItem[]>();
}

// templates/solidjs/src/components/ModusStepper.tsx
import { createEffect, type Component } from "solid-js";

export type StepperColor =
  | "primary"
  | "secondary"
  | "accent"
  | "info"
  | "success"
  | "warning"
  | "error"
  | "neutral";

/**
 * Represents a single step in a stepper component.
 */
export interface ModusStepperItem {
  label?: string;
  color?: StepperColor;
  content?: string;
  customClass?: string;
}

/**
 * Props for the ModusStepper component.
 */
export interface ModusStepperProps {
  steps: ModusStepperItem[];
  orientation?: "horizontal" | "vertical";
  customClass?: string;
  ariaLabel?: string;
}

/**
 * Renders a Modus stepper component.
 * @param {ModusStepperProps} props - The component props.
 * @returns {JSX.Element} The rendered stepper component.
 */
const ModusStepper: Component<ModusStepperProps> = (props) => {
  let stepperEl: HTMLElement | undefined;

  createEffect(() => {
    const stepper = stepperEl as { steps?: ModusStepperItem[]; customClass?: string } | undefined;
    if (!stepper) return;
    stepper.steps = props.steps.map((step) => ({ ...step }));
  });

  createEffect(() => {
    const stepper = stepperEl as { customClass?: string } | undefined;
    if (!stepper) return;
    stepper.customClass = props.customClass;
  });

  return (
    <modus-wc-stepper
      ref={(el) => (stepperEl = el as HTMLElement)}
      orientation={props.orientation ?? "horizontal"}
      aria-label={props.ariaLabel ?? "Workflow progress"}
      custom-class={props.customClass}
    />
  );
};

export default ModusStepper;
