// templates/angular/src/app/components/modus-autocomplete.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModusWcAutocomplete } from '@trimble-oss/moduswebcomponents-angular';
import type {
  Components,
  IAutocompleteItem,
  IAutocompleteNoResults,
  ModusSize,
} from '@trimble-oss/moduswebcomponents';

/**
 * Props supported by the {@link ModusAutocompleteComponent}.
 */
export interface ModusAutocompleteProps {
  /** Indicates that the autocomplete should have a border. */
  bordered?: Components.ModusWcAutocomplete['bordered'];
  /** Custom CSS class applied to the host element. */
  className?: Components.ModusWcAutocomplete['customClass'];
  /** The debounce timeout in milliseconds. Set to 0 to disable debouncing. */
  debounceMs?: Components.ModusWcAutocomplete['debounceMs'];
  /** Disables the autocomplete. */
  disabled?: Components.ModusWcAutocomplete['disabled'];
  /** Show the clear button within the input field. */
  includeClear?: Components.ModusWcAutocomplete['includeClear'];
  /** Show the search icon within the input field. */
  includeSearch?: Components.ModusWcAutocomplete['includeSearch'];
  /** The ID of the input element. */
  inputId?: Components.ModusWcAutocomplete['inputId'];
  /** Tab index applied to the input. */
  inputTabIndex?: Components.ModusWcAutocomplete['inputTabIndex'];
  /** The items to display in the menu. */
  items?: IAutocompleteItem[];
  /** Label text displayed above the autocomplete. */
  label?: Components.ModusWcAutocomplete['label'];
  /** Whether the menu should remain open after an item is selected. */
  leaveMenuOpen?: Components.ModusWcAutocomplete['leaveMenuOpen'];
  /** The minimum number of characters required to render the menu. */
  minChars?: Components.ModusWcAutocomplete['minChars'];
  /** Whether the input allows multiple items to be selected. */
  multiSelect?: Components.ModusWcAutocomplete['multiSelect'];
  /** Name attribute submitted in forms. */
  name?: Components.ModusWcAutocomplete['name'];
  /** The content to display when no results are found. */
  noResults?: IAutocompleteNoResults;
  /** Placeholder text displayed when empty. */
  placeholder?: Components.ModusWcAutocomplete['placeholder'];
  /** Prevents editing when true. */
  readOnly?: Components.ModusWcAutocomplete['readOnly'];
  /** Marks the field as required. */
  required?: Components.ModusWcAutocomplete['required'];
  /** Whether to show the menu whenever the input has focus. */
  showMenuOnFocus?: Components.ModusWcAutocomplete['showMenuOnFocus'];
  /** The size of the autocomplete (input and menu). */
  size?: ModusSize;
  /** A spinner that appears when set to true. */
  showSpinner?: Components.ModusWcAutocomplete['showSpinner'];
  /** Current input value. */
  value?: Components.ModusWcAutocomplete['value'];
  /** Maximum number of chips to display. */
  maxChips?: Components.ModusWcAutocomplete['maxChips'];
  /** Custom item selection handler. */
  customItemSelect?: Components.ModusWcAutocomplete['customItemSelect'];
  /** Custom input change handler. */
  customInputChange?: Components.ModusWcAutocomplete['customInputChange'];
  /** Custom key down handler. */
  customKeyDown?: Components.ModusWcAutocomplete['customKeyDown'];
  /** Custom blur handler. */
  customBlur?: Components.ModusWcAutocomplete['customBlur'];
  /** Minimum width for the text input in pixels. */
  minInputWidth?: Components.ModusWcAutocomplete['minInputWidth'];
}

/**
 * Angular wrapper for the Modus autocomplete web component.
 *
 * The autocomplete component supports custom menu items and custom icons via slots:
 * - `menu-items` slot: For custom menu item content
 * - `custom-icon` slot: For custom icon in the input field
 *
 * @example
 * ```html
 * <modus-autocomplete
 *   label="Search"
 *   [items]="searchItems"
 *   [value]="searchValue()"
 *   (itemSelect)="handleItemSelect($event)"
 * />
 * ```
 */
@Component({
  selector: 'modus-autocomplete',
  imports: [CommonModule, ModusWcAutocomplete],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-wc-autocomplete
      [bordered]="bordered()"
      [customClass]="className()"
      [debounceMs]="debounceMs()"
      [disabled]="disabled()"
      [includeClear]="includeClear()"
      [includeSearch]="includeSearch()"
      [inputId]="inputId()"
      [inputTabIndex]="inputTabIndex()"
      [items]="items()"
      [label]="label()"
      [leaveMenuOpen]="leaveMenuOpen()"
      [minChars]="minChars()"
      [multiSelect]="multiSelect()"
      [name]="name()"
      [noResults]="noResults()"
      [placeholder]="placeholder()"
      [readOnly]="readOnly()"
      [required]="required()"
      [showMenuOnFocus]="showMenuOnFocus()"
      [size]="size()"
      [showSpinner]="showSpinner()"
      [value]="value()"
      [maxChips]="maxChips()"
      [customItemSelect]="customItemSelect()"
      [customInputChange]="customInputChange()"
      [customKeyDown]="customKeyDown()"
      [customBlur]="customBlur()"
      [minInputWidth]="minInputWidth()"
      (chipRemove)="handleChipRemove($event)"
      (chipsExpansionChange)="handleChipsExpansionChange($event)"
      (inputBlur)="handleBlur($event)"
      (inputChange)="handleChange($event)"
      (inputFocus)="handleFocus($event)"
      (itemSelect)="handleItemSelect($event)"
    >
      <ng-content select="[slot='menu-items']" slot="menu-items" />
      <ng-content select="[slot='custom-icon']" slot="custom-icon" />
    </modus-wc-autocomplete>
  `,
})
export class ModusAutocompleteComponent {
  /** Indicates that the autocomplete should have a border. */
  readonly bordered = input<boolean | undefined>(true);

  /** Custom CSS class applied to the host element. */
  readonly className = input<string | undefined>();

  /** The debounce timeout in milliseconds. Set to 0 to disable debouncing. */
  readonly debounceMs = input<number | undefined>(300);

  /** Disables the autocomplete. */
  readonly disabled = input<boolean | undefined>(false);

  /** Show the clear button within the input field. */
  readonly includeClear = input<boolean | undefined>(false);

  /** Show the search icon within the input field. */
  readonly includeSearch = input<boolean | undefined>(false);

  /** The ID of the input element. */
  readonly inputId = input<string | undefined>();

  /** Tab index applied to the input. */
  readonly inputTabIndex = input<number | undefined>();

  /** The items to display in the menu. */
  readonly items = input<IAutocompleteItem[] | undefined>([]);

  /** Label text displayed above the autocomplete. */
  readonly label = input<string | undefined>();

  /** Whether the menu should remain open after an item is selected. */
  readonly leaveMenuOpen = input<boolean | undefined>(false);

  /** The minimum number of characters required to render the menu. */
  readonly minChars = input<number>(0);

  /** Whether the input allows multiple items to be selected. */
  readonly multiSelect = input<boolean | undefined>(false);

  /** Name attribute submitted in forms. */
  readonly name = input<string | undefined>();

  /** The content to display when no results are found. */
  readonly noResults = input<IAutocompleteNoResults | undefined>();

  /** Placeholder text displayed when empty. */
  readonly placeholder = input<string>('');

  /** Prevents editing when true. */
  readonly readOnly = input<boolean | undefined>(false);

  /** Marks the field as required. */
  readonly required = input<boolean | undefined>(false);

  /** Whether to show the menu whenever the input has focus. */
  readonly showMenuOnFocus = input<boolean | undefined>(false);

  /** The size of the autocomplete (input and menu). */
  readonly size = input<ModusSize | undefined>('md');

  /** A spinner that appears when set to true. */
  readonly showSpinner = input<boolean | undefined>(false);

  /** Current input value. */
  readonly value = input<string>('');

  /** Maximum number of chips to display. */
  readonly maxChips = input<number | undefined>(-1);

  /** Custom item selection handler. */
  readonly customItemSelect = input<((item: IAutocompleteItem) => void) | undefined>();

  /** Custom input change handler. */
  readonly customInputChange = input<((value: string) => void) | undefined>();

  /** Custom key down handler. */
  readonly customKeyDown = input<((event: KeyboardEvent) => void) | undefined>();

  /** Custom blur handler. */
  readonly customBlur = input<((event: FocusEvent) => void) | undefined>();

  /** Minimum width for the text input in pixels. */
  readonly minInputWidth = input<number | undefined>(10);

  /** Emits when a selected item chip is removed. */
  readonly chipRemove = output<IAutocompleteItem>();

  /** Emits when chips expansion state changes. */
  readonly chipsExpansionChange = output<{ expanded: boolean }>();

  /** Emits when the input loses focus. */
  readonly inputBlur = output<FocusEvent>();

  /** Emits when the input value changes. */
  readonly inputChange = output<Event>();

  /** Emits when the input gains focus. */
  readonly inputFocus = output<FocusEvent>();

  /** Emits when a menu item is selected. */
  readonly itemSelect = output<IAutocompleteItem>();

  handleChipRemove(event: CustomEvent<IAutocompleteItem>): void {
    this.chipRemove.emit(event.detail);
  }

  handleChipsExpansionChange(event: CustomEvent<{ expanded: boolean }>): void {
    this.chipsExpansionChange.emit(event.detail);
  }

  handleBlur(event: CustomEvent<FocusEvent>): void {
    this.inputBlur.emit(event.detail);
  }

  handleChange(event: CustomEvent<Event>): void {
    this.inputChange.emit(event.detail);
  }

  handleFocus(event: CustomEvent<FocusEvent>): void {
    this.inputFocus.emit(event.detail);
  }

  handleItemSelect(event: CustomEvent<IAutocompleteItem>): void {
    this.itemSelect.emit(event.detail);
  }
}

// templates/solidjs/src/components/ModusAutocomplete.tsx
import { createEffect } from "solid-js";
import type { Component, JSX } from "solid-js";

/**
 * Represents an item in the autocomplete list.
 */
export interface AutocompleteItem {
  /** The label to display for the item. */
  label: string;
  /** The value of the item. */
  value: string;
  /** Whether the item is visible in the menu. */
  visibleInMenu: boolean;
  /** Whether the item is selected. */
  selected?: boolean;
}

/**
 * Represents the content to display when there are no results.
 */
export interface AutocompleteNoResults {
  /** The main label to display. */
  label: string;
  /** A sub-label to display. */
  subLabel: string;
  /** The severity of the message. */
  severity?: "error" | "info" | "success" | "warning";
}

/**
 * Props for the ModusAutocomplete component.
 */
export interface ModusAutocompleteProps {
  /** Whether the autocomplete has a border. */
  bordered?: boolean;
  /** Whether the autocomplete is disabled. */
  disabled?: boolean;
  /** Whether multiple items can be selected. */
  multiSelect?: boolean;
  /** The items to display in the autocomplete list. */
  items: AutocompleteItem[];
  /** The value of the autocomplete. */
  value?: string;
  /** The placeholder text for the input. */
  placeholder?: string;
  /** The label for the autocomplete. */
  label?: string;
  /** The size of the autocomplete. */
  size?: "sm" | "md" | "lg";
  /** The debounce time in milliseconds for input changes. */
  debounceMs?: number;
  /** The minimum number of characters to trigger the autocomplete. */
  minChars?: number;
  /** Whether to leave the menu open after an item is selected. */
  leaveMenuOpen?: boolean;
  /** Whether to show a spinner. */
  showSpinner?: boolean;
  /** The content to display when there are no results. */
  noResults?: AutocompleteNoResults;
  /** A custom CSS class to apply to the autocomplete. */
  customClass?: string;
  /** Whether the autocomplete is read-only. */
  readOnly?: boolean;
  /** Whether the autocomplete is required. */
  required?: boolean;
  /** The ID of the input element. */
  inputId?: string;
  /** The tab index of the input element. */
  inputTabIndex?: number;
  /** The name of the input element. */
  name?: string;
  /** The ARIA label for the autocomplete. */
  "aria-label"?: string;
  /** A callback function to handle input changes. */
  onInputChange?: (event: CustomEvent<Event>) => void;
  /** A callback function to handle input focus. */
  onInputFocus?: (event: CustomEvent<FocusEvent>) => void;
  /** A callback function to handle input blur. */
  onInputBlur?: (event: CustomEvent<FocusEvent>) => void;
  /** A callback function to handle item selection. */
  onItemSelect?: (event: CustomEvent<AutocompleteItem>) => void;
  /** A callback function to handle chip removal. */
  onChipRemove?: (event: CustomEvent<AutocompleteItem>) => void;
  /** The content to display inside the autocomplete. */
  children?: JSX.Element;
}

/**
 * Renders a Modus autocomplete component.
 * @param props - The component props.
 * @returns The rendered autocomplete component.
 */
const ModusAutocomplete: Component<ModusAutocompleteProps> = (props) => {
  let autocompleteEl: HTMLModusWcAutocompleteElement | undefined;

  createEffect(() => {
    const autocomplete = autocompleteEl;
    if (!autocomplete) return;

    const handleInputChange = (event: Event) => {
      props.onInputChange?.(event as CustomEvent<Event>);
    };
    const handleInputFocus = (event: Event) => {
      props.onInputFocus?.(event as CustomEvent<FocusEvent>);
    };
    const handleInputBlur = (event: Event) => {
      props.onInputBlur?.(event as CustomEvent<FocusEvent>);
    };
    const handleItemSelect = (event: Event) => {
      props.onItemSelect?.(event as CustomEvent<AutocompleteItem>);
    };
    const handleChipRemove = (event: Event) => {
      props.onChipRemove?.(event as CustomEvent<AutocompleteItem>);
    };

    if (props.onInputChange)
      autocomplete.addEventListener("inputChange", handleInputChange);
    if (props.onInputFocus)
      autocomplete.addEventListener("inputFocus", handleInputFocus);
    if (props.onInputBlur)
      autocomplete.addEventListener("inputBlur", handleInputBlur);
    if (props.onItemSelect)
      autocomplete.addEventListener("itemSelect", handleItemSelect);
    if (props.onChipRemove)
      autocomplete.addEventListener("chipRemove", handleChipRemove);

    return () => {
      if (props.onInputChange)
        autocomplete.removeEventListener("inputChange", handleInputChange);
      if (props.onInputFocus)
        autocomplete.removeEventListener("inputFocus", handleInputFocus);
      if (props.onInputBlur)
        autocomplete.removeEventListener("inputBlur", handleInputBlur);
      if (props.onItemSelect)
        autocomplete.removeEventListener("itemSelect", handleItemSelect);
      if (props.onChipRemove)
        autocomplete.removeEventListener("chipRemove", handleChipRemove);
    };
  });

  return (
    <modus-wc-autocomplete
      ref={(el) => (autocompleteEl = el)}
      bordered={props.bordered ?? true}
      disabled={props.disabled ?? false}
      multiSelect={props.multiSelect ?? false}
      items={props.items}
      value={props.value ?? ""}
      placeholder={props.placeholder}
      label={props.label}
      size={props.size ?? "md"}
      debounceMs={props.debounceMs ?? 300}
      minChars={props.minChars ?? 0}
      leaveMenuOpen={props.leaveMenuOpen ?? false}
      showSpinner={props.showSpinner ?? false}
      noResults={props.noResults}
      customClass={props.customClass}
      readOnly={props.readOnly ?? false}
      required={props.required ?? false}
      inputId={props.inputId}
      inputTabIndex={props.inputTabIndex}
      name={props.name}
      aria-label={props["aria-label"]}
    >
      {props.children}
    </modus-wc-autocomplete>
  );
};

export default ModusAutocomplete;
