// templates/angular/src/app/dev/theme-switcher-dropdown/theme-switcher-dropdown.component.ts
import { ChangeDetectionStrategy, Component, computed, inject } from '@angular/core';
import { ThemeService, ThemeMode, ThemeName } from '../../services/theme.service';
import { ModusDropdownMenuComponent } from '../../components/modus-dropdown-menu.component';
import { ModusMenuComponent } from '../../components/modus-menu.component';
import { ModusMenuItemComponent } from '../../components/modus-menu-item.component';

interface ThemeOption {
  value: string;
  label: string;
  description: string;
}

/**
 * Theme switcher dropdown for the Dev Panel.
 *
 * Provides a dropdown menu with all 6 Modus themes:
 * - Classic Light/Dark
 * - Modern Light/Dark
 * - Connect Light/Dark
 */
@Component({
  selector: 'app-theme-switcher-dropdown',
  standalone: true,
  imports: [ModusDropdownMenuComponent, ModusMenuComponent, ModusMenuItemComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <modus-dropdown-menu
      buttonAriaLabel="Theme selection menu"
      [buttonColor]="'tertiary'"
      [buttonVariant]="'filled'"
      [menuPlacement]="'bottom-end'"
    >
      <div slot="button" class="flex items-center justify-between w-full min-w-[140px] px-3 py-2 gap-2">
        <div class="flex-1 text-left text-base font-medium">
          {{ getCurrentThemeLabel() }}
        </div>
        <i class="modus-icons text-base shrink-0">expand_more</i>
      </div>
      <div slot="menu">
        <modus-menu>
          @for (theme of themes; track theme.value) {
            <modus-menu-item
              [label]="theme.label"
              [value]="theme.value"
              [selected]="isThemeSelected(theme.value)"
              (itemSelect)="onThemeSelect(theme.value)"
            />
          }
        </modus-menu>
      </div>
    </modus-dropdown-menu>
  `,
})
export class ThemeSwitcherDropdownComponent {
  private readonly themeService = inject(ThemeService);

  readonly currentTheme = computed(() => this.themeService.theme());
  readonly currentMode = computed(() => this.themeService.mode());

  readonly themes: ThemeOption[] = [
    {
      value: 'modus-classic-light',
      label: 'Classic Light',
      description: 'Traditional light theme',
    },
    {
      value: 'modus-classic-dark',
      label: 'Classic Dark',
      description: 'Traditional dark theme',
    },
    {
      value: 'modus-modern-light',
      label: 'Modern Light',
      description: 'Contemporary light theme',
    },
    {
      value: 'modus-modern-dark',
      label: 'Modern Dark',
      description: 'Contemporary dark theme',
    },
    {
      value: 'connect-light',
      label: 'Connect Light',
      description: 'Connect light theme',
    },
    {
      value: 'connect-dark',
      label: 'Connect Dark',
      description: 'Connect dark theme',
    },
  ];

  getCurrentThemeLabel(): string {
    const theme = this.currentTheme();
    const mode = this.currentMode();

    let themeLabel: string;
    switch (theme) {
      case 'modus-classic':
        themeLabel = 'Classic';
        break;
      case 'modus-modern':
        themeLabel = 'Modern';
        break;
      case 'connect':
        themeLabel = 'Connect';
        break;
      default:
        themeLabel = theme;
    }

    const modeLabel = mode === 'light' ? 'Light' : 'Dark';
    return `${themeLabel} ${modeLabel}`;
  }

  isThemeSelected(value: string): boolean {
    const fullTheme = `${this.currentTheme()}-${this.currentMode()}`;
    return fullTheme === value;
  }

  onThemeSelect(value: string): void {
    const parts = value.split('-');
    if (parts.length < 2) {
      return;
    }

    const mode = parts[parts.length - 1] as ThemeMode;
    const theme = parts.slice(0, -1).join('-') as ThemeName;

    if (theme && mode && (mode === 'light' || mode === 'dark')) {
      this.themeService.setTheme(theme, mode);
    }
  }
}

// templates/solidjs/src/components/ThemeSwitcherDropdown.tsx
import { createSignal, onMount, type Component } from "solid-js";
import { Show } from "solid-js";
import { useTheme } from "../contexts/ThemeContext";
import type { Theme } from "../contexts/ThemeContext";
import ModusDropdownMenu from "./ModusDropdownMenu";
import type { MenuItem } from "./ModusMenu";

/**
 * Props for the ThemeSwitcherDropdown component.
 */
interface ThemeSwitcherDropdownProps {
  className?: string;
}

/**
 * Renders the content of the theme switcher dropdown.
 * @param {ThemeSwitcherDropdownProps} props - The component props.
 * @returns {JSX.Element} The rendered dropdown content.
 */
const themeOptions: { value: Theme; label: string }[] = [
  { value: "modus-classic-light", label: "Classic Light" },
  { value: "modus-classic-dark", label: "Classic Dark" },
  { value: "modus-modern-light", label: "Modern Light" },
  { value: "modus-modern-dark", label: "Modern Dark" },
  { value: "connect-light", label: "Connect Light" },
  { value: "connect-dark", label: "Connect Dark" },
];

const menuItems: MenuItem[] = themeOptions.map((t) => ({
  label: t.label,
  value: t.value,
}));

const ThemeSwitcherDropdownContent: Component<ThemeSwitcherDropdownProps> = (props) => {
  const { theme, setTheme } = useTheme();

  const handleItemSelect = (event: CustomEvent<{ value: string }>) => {
    const selectedValue = event.detail.value as Theme;
    if (selectedValue && selectedValue !== theme()) {
      setTheme(selectedValue);
    }
  };

  const getCurrentThemeLabel = () => {
    const found = themeOptions.find((t) => t.value === theme());
    return found ? found.label : "Theme";
  };

  return (
    <div class={props.className ?? ""}>
      <ModusDropdownMenu
        buttonVariant="filled"
        menuPlacement="bottom-end"
        menuItems={menuItems}
        selectedValue={theme()}
        onItemSelect={handleItemSelect}
        buttonContent={
          <div class="flex items-center justify-between w-full min-w-[140px] px-3 py-2 gap-2">
            <div class="flex-1 text-left text-md font-medium">
              {getCurrentThemeLabel()}
            </div>
            <i class="modus-icons text-base flex-shrink-0">expand_more</i>
          </div>
        }
      />
    </div>
  );
};

/**
 * Renders the theme switcher dropdown with hydration-safe mounting.
 * @param {ThemeSwitcherDropdownProps} props - The component props.
 * @returns {JSX.Element} The rendered component.
 */
const ThemeSwitcherDropdown: Component<ThemeSwitcherDropdownProps> = (props) => {
  const [mounted, setMounted] = createSignal(false);

  onMount(() => {
    setMounted(true);
  });

  return (
    <Show
      when={mounted()}
      fallback={
        <div class={props.className ?? ""}>
          <div class="animate-pulse">
            <div class="h-8 w-32 rounded bg-muted" />
          </div>
        </div>
      }
    >
      <ThemeSwitcherDropdownContent className={props.className} />
    </Show>
  );
};

export default ThemeSwitcherDropdown;
