// templates/react/src/components/DemoExample.tsx
import type { ReactNode } from "react";

/**
 * Props for the DemoExample component.
 */
interface DemoExampleProps {
  /** The title of the demo example. */
  title: string;
  /** A description of the demo example. */
  description: string | ReactNode;
  /** The content of the demo example. */
  children: ReactNode;
}

/**
 * Renders a styled container for a demo example.
 * @param {DemoExampleProps} props - The component props.
 * @param {string} props.title - The title of the demo example.
 * @param {string | ReactNode} props.description - A description of the demo example.
 * @param {ReactNode} props.children - The content of the demo example.
 * @returns {JSX.Element} The rendered demo example component.
 */
export default function DemoExample({
  title,
  description,
  children,
}: DemoExampleProps) {
  return (
    <div className="flex flex-col gap-4 rounded-lg bg-background p-6 border-default">
      <div className="flex flex-col gap-1">
        <div className="text-lg font-medium text-foreground">{title}</div>
        <div className="text-sm text-foreground opacity-80">{description}</div>
      </div>
      <div className="flex flex-col gap-4">{children}</div>
    </div>
  );
}

/**
 * Renders a clean, unstyled container for a demo example.
 * @param {DemoExampleProps} props - The component props.
 * @param {string} props.title - The title of the demo example.
 * @param {string | ReactNode} props.description - A description of the demo example.
 * @param {ReactNode} props.children - The content of the demo example.
 * @returns {JSX.Element} The rendered clean demo example component.
 */
export function DemoExampleClean({
  title,
  description,
  children,
}: DemoExampleProps) {
  return (
    <div className="flex flex-col gap-4 rounded-lg bg-background p-6 border-dashed">
      <div className="flex flex-col gap-1">
        <div className="text-lg font-medium text-foreground">{title}</div>
        <div className="text-sm text-foreground opacity-80">{description}</div>
      </div>
      <div className="flex flex-col gap-4">{children}</div>
    </div>
  );
}

// templates/angular/src/app/components/demos/demo-example.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';

/**
 * Renders a styled container for a demo example.
 *
 * Provides a card-based container with:
 * - Title and description
 * - Content projection for example content
 * - Consistent styling using design system colors
 *
 * @example
 * ```html
 * <demo-example title="Button Variants" description="Different button styles">
 *   <modus-button>Primary</modus-button>
 * </demo-example>
 * ```
 */
@Component({
  selector: 'demo-example',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-col gap-4 rounded-lg p-6 border-default border-1px">
      <div class="flex flex-col gap-1">
        <div class="text-lg font-medium text-foreground">{{ title() }}</div>
        <div class="text-sm text-foreground-80">{{ description() }}</div>
      </div>
      <div class="flex flex-col gap-4">
        <ng-content />
      </div>
    </div>
  `,
})
export class DemoExampleComponent {
  /** The title of the demo example */
  readonly title = input.required<string>();

  /** A description of the demo example */
  readonly description = input<string>('');
}
