// templates/react/src/main.tsx
// Set asset path BEFORE any component imports
import { setAssetPath } from "@trimble-oss/moduswebcomponents/components";
setAssetPath(window.location.origin + "/modus-wc/");

import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.tsx";

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// templates/solidjs/src/index.tsx
import { setAssetPath } from "@trimble-oss/moduswebcomponents/components";
setAssetPath(window.location.origin + "/modus-wc/");

import { defineCustomElements } from "@trimble-oss/moduswebcomponents/loader";
defineCustomElements();

import { render } from "solid-js/web";
import App from "./App";
import "./index.css";

render(() => <App />, document.getElementById("root")!);
